### ISSUE TITLE
Game putting you in somesort of Spectator mode in servers when you join

### ISSUE THREAD

**Issue by RebornTrack970** [Anuken/Mindustry#4800] opened 2021-02-26 16:23 UTC
**Platform**: *Windows*

**Build**: *125.1*

**Issue**: *When i join to a server, it sometimes puts me in a kinda spectator state, it happens rarely and i dont know what causes it. I cant spawn, cant interact, cant view players. However, i am in the same team as them, i can chat, i can see block changes and the chat.*

**Steps to reproduce**: *It is a rare thing that hapoens when yiu join servers.*

**Link(s) to mod(s) used**: *None*

**Save file**: *Happened on multiple servers at multiple saves.*

**(Crash) logs**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2021-02-26 16:26
>  it happens rarely and i dont know what causes it.

As mentioned in Discord - can't reproduce, won't fix.

**Comment by RebornTrack970** [comment] 2021-02-26 16:27
F
I will try to record if it happens again.

**Closed by Anuken** 2021-02-26 16:26 UTC
Labels: bug

**Comment by Anuken** [comment] 2021-02-26 16:27
That doesn't help either - unless I know what makes it happen, seeing you 'in spectator mode' won't show me what the root cause is at all.
