### ISSUE TITLE
Campaign saves being replaced

### ISSUE THREAD

**Issue by BassBro** [Anuken/Mindustry#2620] opened 2020-09-19 19:58 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*
Mac
**Build**: *The build number under the title in the main menu. Required.*
steam build 105
**Issue**: *Explain your issue in detail.*
i went into the campaign and my frozen forest progress had been overridden with an editor map i was messing around with
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i was in the editor and i left the editor opened the campaign and clicked on frozen forest, then i noticed that it said 'frozen forest' with icons for copper lead and coal, it didn't say amounts of any resource even though i had about 20 minutes of progress, when i opened the map frozen forest did not appear, that same map i had open in the editor opened, when i left i re-opened the campaign and saw that my progress was straight up gone.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
none
**Save file**: *The save file you were playing on when the bug happened, if applicable.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-09-19 20:03
> i was in the editor

What were you doing before the editor?

**Comment by Charlignon** [comment] 2020-09-20 11:40
Hello, I'd like to second this issue, I experiences a very similar issue which I describe below.

**Platform:** Linux (Ubuntu 18.04.5 LTS)
**Build:** alpha build 105

**Issue:**
This occurred in 3 steps :
1. After some time of playing, one sector (A) on the map was not displaying the correct amount of resources. When trying to load it, it would load another sector (B) instead (always the same)
2. After restarting the game and reentering campaign mode, the inaccessible sector A did not appear. After loading the second sector B, the map did displayed A but back to step 1 bug.
3. After B saved a few times, A would displayed as locked forever. (this is the current state of the save file)

_A = sector 63
B = sector 142_

**Steps to reproduce:**
On **A,** I replaced the base 3x3x core with the direct upgrade (4x4) 
I then on **B**, and waited for resources to stack. Then I upgraded the core on this one too.
I tried to go back to **A**, but the **B** save loaded instead. This is step 1.
I used the Save & Quit menu to reload the campaign, it leaded to step 2. It stayed in this state for a few tries, I also experimented loading other sectors, exiting the game without saving (alt+F4), etc.
Finally, the autosave occurred when I was on **B**, leading to step 3.

**Link(s) to mod(s) used:** None
**Save file:** [saves-charlignon-issue-2620.zip](https://github.com/Anuken/Mindustry/files/5251563/saves-charlignon-issue-2620.zip)
**Crash report:** None

**Comment by Charlignon** [comment] 2020-09-20 12:26
Correction : I tried loading the save separately on a blank campaign since I have a backup, and it appears that the sector 63 save now contains the sector 170 map, on which I incidentally upgraded the core too. However, I didn't saved this action, so the core is not replaced on it.
In short, in the attached zip above, sector 63 is overridden by sector 171.

I will experiment a little more, and since the tech tree is stored separately, I will be able to reproduce the core thingy.

**Comment by Anuken** [comment] 2020-09-20 18:37
Here's what I tried with your saves:
- Rapidly switching before sectors ~10 times
- Slowly switching sectors to let autosave trigger
- Upgrading cores on sectors, then waiting for autosave and switching
- Opening the editor, saving, closing it and checking a sector
- Opening the editor, editing in-game, closing, saving, and checking as sector
- Opening a sector, exiting it then doing the sequence above
- Loading your save from sector 63 to see if it had any evidence *(it didn't)*

None of these produced the results in this issue. Are you sure nothing else of interest happened while you were playing?

**Comment by Charlignon** [comment] 2020-09-20 19:43
Your're right, I couldn't reproduce it either. 
If it means anything, I left my game on pause (escape menu) for all night on sector 63 right after unlocking core upgrade. What I describe above happened the day after I paused the game. When I started, I just did the upgrade (~1mn) and then switched to the other sector right after that.

**Comment by Charlignon** [comment] 2020-09-21 13:38
I just reproduced it, it may be related to the long pause after all.
I'll name the sectors A and B as the sector does not matter. Just note that they are both captured.
1. I left my game on pause on sector A for some time (1h I think)
2. I resumed the game, built 2 thingy (10 seconds), and almost immediately switched to sector B
3. I spent about 5mn on B to let it time to autosave 
4. Back on the map > A is overridden by B. Moreover, A contains B save + 5mn played, while B contains its save _before_ the 5mn

Additional tests :
- I do changes on A, let autosave, then go back to B, make some changes, let autosave : A is overridden again, I deduce that in this state B will never stop overwriting A
- Save & quit does not override A
- After a save and quit, the overwriting does not occur anymore (A and B are treated as two separate maps, day/night time is different between the 2)
- I couldn't make the sector A disappear like the first time

I did backuped the saves before these additional tests, I'm not sure if they are any use but feel free to ask

**Comment by 50275** [comment] 2020-09-24 19:50
Sometimes, when I go back to a sector, it tells me "An error has occured Save file corrupted or invalid!" then acts as if I just launched there; my base disappears and I am back at wave 1 with the starting resources I launched.

**Comment by Anuken** [comment] 2020-09-24 20:04
> I played on bleeding edge build 9871 then loaded the file on alpha build 105 if that matters.

That matter significantly. Never mix BE and release versions, they're not forward compatible.

**Comment by potatoisagender** [comment] 2020-09-25 22:40
> Sometimes, when I go back to a sector, it tells me "An error has occured Save file corrupted or invalid!" then acts as if I just launched there; my base disappears and I am back at wave 1 with the starting resources I launched."
My game just did this, and all I did was update the game from be to newer be.

**Comment by quanium** [comment] 2020-09-26 06:00
https://github.com/Anuken/Mindustry/issues/2678#issuecomment-697356898

**Comment by mse-k** [comment] 2020-10-04 01:19
my theory is that the game stores the sectors you were in in ram if you were playing them for a while so you can switch back faster

open sector code sus

but what im thinking is if it does keep them in RAM then it might NOT put it in ram if there was already a save there but will say that it is, this would explain it replacing the save in both cases

in the editor then going to campaign it had tried to save frozen forest into RAM and said it did but it actually didnt so it opened to the editor map

in the other case it saved sector A in ram and when you moved to B it thought it had saved it into ram but it didnt, making it read A, even after trying again it will still read from A but after restart it will have cleared out its ram and will no longer see anything saved there so it will look for the save file from disc

all of this is assuming the game actually saves maps ect into ram when you leave them for a while but i could be wrong about that

**Comment by mse-k** [comment] 2020-10-04 01:20
also tl;dr if the game saves maps into ram when it opens them i could be trying to saving maps in but not actually doing it but saying it did causing it to open the old map when you want to open the map that was saved in ram

**Comment by Anuken** [comment] 2020-10-16 21:04
Does this still happen regularly to anyone, and if so, have any specific circumstances been determined?

**Comment by potatoisagender** [comment] 2020-10-16 21:05
haven't tried to play campaign yet. I can test though.

**Comment by ML-10** [comment] 2020-10-16 21:07
My save file had been replaced version v107 when going on a newer version save 
I think it's only because of older version files because it said save file corrupted. Thank you Anuken!

**Comment by Anuken** [comment] 2020-10-17 17:13
Closing until someone else can reproduce it.

**Closed by Anuken** 2020-10-17 17:13 UTC
Labels: bug
