### ISSUE TITLE
Auto save's aren't reliable.

### ISSUE THREAD

**Issue by bartox1** [Anuken/Mindustry#2629] opened 2020-09-20 15:23 UTC
**Platform**:Windows

**Build**: steam build 105

**Issue**: Auto-save's , very rarely are deleted from campain.

**Steps to reproduce**: Close Mindustry by shuting down the computer by unpluging it from power.(most likley when the game is preforming an auto-save)

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-09-20 17:14
Probably duplicate of #2620

**Closed by Anuken** 2020-09-20 17:14 UTC
Labels: bug
