### ISSUE TITLE
Player camera

### ISSUE THREAD

**Issue by D-player1** [Anuken/Mindustry#2487] opened 2020-09-05 09:50 UTC
**Platform**: Android

**Build**: 104.6

**Issue**: Player camera uncontrollably moving to the direction where the player swipes

**Steps to reproduce**: Set respawn time to 0, swipe the screen at the very start of a game

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment] 2020-09-05 10:11
Please try the [latest build](https://github.com/Anuken/MindustryBuilds/releases/latest) to see if the issue is still there, since a lot has changed, and is thus likely not there anymore. 🤔

**Comment by D-player1** [comment] 2020-09-05 10:20
> Please try the [latest build](https://github.com/Anuken/MindustryBuilds/releases/latest) to see if the issue is still there, since a lot has changed, and is thus likely not there anymore. 🤔

There's no respawn time there

**Comment by Quezler** [comment] 2020-09-05 10:25
well then, that means you can close this issue 🙂

**Comment by grimsoul10** [comment] 2020-09-05 11:01
> There's no respawn time there
Nope, u can do that Bug without setting respawn time, just swipe camera while core go to ground...

**Comment by Anuken** [comment] 2020-09-05 12:42
Not relevant in v6.

**Closed by Anuken** 2020-09-05 12:42 UTC
Labels: bug
