### ISSUE TITLE
F-droid build is highly outdated

### ISSUE THREAD

**Issue by MCWertGaming** [Anuken/Mindustry#5156] opened 2021-04-26 10:22 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*
Android

**Issue**: *Explain your issue in detail.*
The F-Droid build is still version 5 (build number 104) from february.

(I have removed the irellevant points)

**Comment by Anuken** [comment] 2021-04-26 12:55
Duplicate of #3823.

**Closed by Anuken** 2021-04-26 12:55 UTC
Labels: bug
