### ISSUE TITLE
crash server in campaign

### ISSUE THREAD

**Issue by Fosdog39** [Anuken/Mindustry#2959] opened 2020-10-15 11:26 UTC
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: *Windows*

**Build**: *108.*

**Issue**: *game crash due to server launch*

**Steps to reproduce**: *entered the campaign, pressed esc, clicked to start the server and the error*

**Link(s) to mod(s) used**: *None*

**Save file**: *[mydata.zip](https://github.com/Anuken/Mindustry/files/5384406/mydata.zip)*

**Crash report**: *[crash-report-10_15_2020_14_08_58.txt](https://github.com/Anuken/Mindustry/files/5384397/crash-report-10_15_2020_14_08_58.txt)*

---

**[x]**

**Comment by Quezler** [comment] 2020-10-15 11:29
duplicate of #2950, #2937 & #2938 (fixed in the latest version, wait for `109` or use a `bleeding edge` build)

**Comment by Fosdog39** [comment] 2020-10-15 11:32
i new downloaded it from itchio :/

**Comment by Quezler** [comment] 2020-10-15 11:33
you can find the `bleeding edge` builds here: https://github.com/Anuken/MindustryBuilds/releases

please close this issue.

**Closed** 2020-10-15 11:34 UTC
Labels: bug
