### ISSUE TITLE
Inconsistent Flyer spawn position

### ISSUE THREAD

**Issue by MikouZonata** [Anuken/Mindustry#1729] opened 2020-03-19 09:55 UTC
**Platform**: Windows 7

**Build**: Steam build 104.6

**Issue**: I expect flying enemies to spawn from a point on the edge of the map closest to their placed Enemy Spawn on the map. Flying enemies instead spawn from a point on the edge of the map a seemingly random x and/or y distance away from the spawn point. This distance is however consistent every time the map is played.
How is this distance generated? Can I set it? Can I preview it?

**Steps to reproduce**:
- Create a new map or edit an existing map from Map Editor.
- Place an Enemy Spawn anywhere on the map and have flying enemies spawn through the Waves system.
- Play the map in Survival mode.

![EditorView](https://user-images.githubusercontent.com/15729844/77054265-dae7ea00-69cf-11ea-8283-3eef65596eb6.png)
![InGame](https://user-images.githubusercontent.com/15729844/77054270-dcb1ad80-69cf-11ea-82e7-abe2bc99b8ed.jpg)

**Comment by QmelZ** [comment] 2020-03-19 10:52
Interesting, i dont get that inconsistency but a bit back from the expected location

**Comment by Anuken** [comment] 2020-03-19 13:24
> How is this distance generated? 

It is based on the angle to the center; flying spawns always occur at the edge of the map with a random offset applied.

> Can I set it? Can I preview it?

No, and no.

This is not a bug; closing.

**Closed by Anuken** 2020-03-19 13:24 UTC

**Comment by MikouZonata** [comment] 2020-03-19 14:59
You can't tell me this is intentional behaviour...

![Offset](https://user-images.githubusercontent.com/15729844/77080904-2dd69700-69fa-11ea-9755-9e0dfcba40fe.jpg)

Removing the random offset or clamping it to a low number of tiles (max 4) would be an easy fix for this issue.

**Comment by Anuken** [comment] 2020-03-19 15:23
I can't tell based on that  screenshot. Send the map.

**Comment by MikouZonata** [comment] 2020-03-19 16:36
Here's the map:
[Giraffe.zip](https://github.com/Anuken/Mindustry/files/4355749/Giraffe.zip)

**Comment by Anuken** [comment] 2020-03-19 16:50
The spawnpoints are chosen like this:

![Screenshot from 2020-03-19 12-42-12](https://user-images.githubusercontent.com/10100000/77092289-0246b300-69e0-11ea-830d-fcb39b7ab77d.png)

![image](https://user-images.githubusercontent.com/10100000/77091486-01615180-69df-11ea-8ed3-93ab79550024.png)

The system was never designed to pick flyer spawns near the ground spawnpoints; only their general direction is used.

**Comment by MikouZonata** [comment] 2020-03-19 17:11
Having to choose between either ground units or air units spawning where you want them to and the other spawning somewhere inconvenient is a pain. Moving this to the feature suggestions hoping it gets changed soon. Thanks for the replies.
