### ISSUE TITLE
No way to listen to music while game runs even with sound at 0%

### ISSUE THREAD

**Issue by andreyorst** [Anuken/Mindustry#1507] opened 2020-02-04 07:36 UTC
**Platform**: *Android*

**Build**: *103.4*

**Issue**: When I start the game my music shuts down it's audio, while still being played. I'm using google play music player and I would like to continue listening while playing Mindastry as it works in other games which can disable in-game music.

**Steps to reproduce**:
1. launch google play music, start playback
2. launch mindastry, start the game
3. Music is not paused, but no audio. In-game audio shutters, music plays silently and songs change.
4. Pause music, ingame audio works fine.

Even if audio is at 0% in settings. Toggle switch also would be nice to have

---

It seems that mindastry tries to make it's audio source higher priority, because two application actually fight for audio output.

**Comment by DeltaNedas** [comment] 2020-02-04 08:06
will try to replicate on simple music player from fdroid and latest master

**Comment by DeltaNedas** [comment] 2020-02-04 09:11
works fine for me, try on BE?
or get https://f-droid.org/en/packages/com.simplemobiletools.musicplayer/ its what i use and ive had no issues with it

**Comment by DeltaNedas** [comment] 2020-02-04 09:16
even my earphone control thingy works, not sure what would cause it to not be muted
very strange

**Comment by andreyorst** [comment] 2020-02-04 10:19
Very weird, but I've tried to do screen capture, but while I was capturing there were no sound issues.

I've downloaded suggested player and it had similar issues, however if I launch mindustry while music plays there's no sound in mindustry. If I pause music, sound in mindustry is back, and after resuming there's no sound in the player itself. If I pause the playback and left my phone after it sleeps music resumes from pause by itself, though it may be player itself.

**Comment by DeltaNedas** [comment] 2020-02-04 11:52
i can listen to hotline miami ost and mindustry music at the same time...
idk man works fine even if i lock and unlock (music doesnt pause but mindustry does, and resumes when locked)
cant replicate, sorry

**Comment by andreyorst** [comment] 2020-02-04 12:23
I've should have mentioned my phone specs: Xiaomi Mi9T with it's stock MiUI10.3.10.0(PFJRUXM) Stable, Android 9. Perhaps let's keep this issue for a while, maybe I'll figure out something or it will be fixed occasionally with future updates.

**Comment by DeltaNedas** [comment] 2020-02-04 13:06
also on android 9, samsung a20e

**Comment by Anuken** [comment] 2020-02-08 01:21
Works fine for me using a different music player; when music is enabled, I can hear both the game music and the player, and when the game music is at 0% everything works normally. I would guess that the issue is caused by your player automatically stopping when **any** track is played in the background, even at 0% volume.

Might be fixed by the next commit; I disabled all `play()` calls when volume is 0.

**Closed** 2020-02-08 01:21 UTC

**Comment by andreyorst** [comment] 2020-02-09 15:08
Thanks for the fix.

> Works fine for me using a different music player; when music is enabled, I
> can hear both the game music and the player, and when the game music is at
> 0% everything works normally.
>
I'll try different players soon. I have Aimp, Poweramp, and shuttle+

I would guess that the issue is caused by your player automatically
> stopping when *any* track is played in the background, even at 0% volume.


I don't think so. When I listen to music and open YouTube video - music is
literally paused.
When I open video in Telegram both music and video are being played at the
same time with no issue (which is not super convenient though).
However, when I launch Mindustry music is silenced, but not paused and
seems like continues to progress very slowly, because if I time launch of
Mindustry at the very end of the track (4-5 seconds remaining) the track
changes after longer time and sound is back until Mindustry plays some of
its sounds.

> Might be fixed by the next commit; I disabled all play() calls when
> volume is 0.
>
This is a good change, will wait for update in Google Play or FDroid,
thanks.

**Comment by andreyorst** [comment] 2020-02-11 04:07
I've tried several players an this happens only with google play music.
However this doesn't happen when I play other games.

Thanks for the fix.
