### ISSUE TITLE
Ошибка при открытии браузера модификаций. 

### ISSUE THREAD

**Issue by kirillkotyatkin** [Anuken/Mindustry#9758] opened 2024-04-20 14:03 UTC
### Platforms

Android

### Build

7.0 146

### Issue

При попытке открыть браузер модов появляется ошибка:
![Screenshot_20240420-163748](https://github.com/Anuken/Mindustry/assets/167627455/cf28a761-8741-4f86-a60b-581203344b9b)

### Steps to reproduce

1.Открываю меню модов. 
2.Открываю браузер модификаций
Через какое-то время появляется ошибка. 

### Save file

[2.zip](https://github.com/Anuken/Mindustry/files/15048452/2.zip)

### (Crash) logs

[Ошибка .pdf](https://github.com/Anuken/Mindustry/files/15048425/default.pdf)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Leo-MathGuy** [comment] 2024-04-20 14:04
Can confirm, have the same issue. For me the steps to reproduce:
* Open mod browser
* Type something in the search bar *before* the mod list is loaded
* Error

**Comment by Anuken** [comment] 2024-04-20 14:16
Cannot reproduce the problem. Network likely blocking the mod list, won't fix.

**Closed by Anuken** 2024-04-20 14:16 UTC
Labels: bug
