### ISSUE TITLE
Mod browser is not working 

### ISSUE THREAD

**Issue by Guyyyyyyyy** [Anuken/Mindustry#8068] opened 2022-12-18 08:20 UTC
**Platform**: `Android 29`

**Build**: `release build 140.4`

**Issue**: *my mod browser is not working .*

**Steps to reproduce**: *i just clicked on the mod browser but it showed this error
> SocketTimeout Failed to connect to raw.githubusercontent.com/49.44.79.236 (port 443) From /26.199.229193 (port 38796) after 2000ms

loBridge.connectErrno: 191

loBridge.connect: 195 PlainSocketImpl.socketConnect: 142

AbstractPlainSocketImpl.doConnect: 390

AbstractPlainSocketImpl.connectToAddress: 230

AbstractPlainSocketImpl.connect 212

SocksSocketImpl.connect: 436 Socket.connect: 691

Platform.connectSocket: 182

RealConnection.connectSocket: 145 RealConnection.connect: 116

StreamAllocation FindConnection: 186

StreamAllocation FindHealthyConnection: 128

StreamAllocation.newStream 97 HttpEngine.connect: 302

HttpEngine.sendRequest 245

HttpURLConnectionimpl.execute: 465

HttpURLConnectionImpl.connect: 191

DelegatingHttpsURLConnection.connect: 90

HttpsURLConnectionImpl.connect: 30

Http HttpRequest block 29

HttpsHttpRequest.lambda$submits

HttpsHttpRequest sr8slembdasuMmrubzSLBskmeN4FKJMTHA SettingsssExternal SyntheticLambdal.run: 219

Executors$RunnableAdapter.call: 462 FutureTask.run: 266

ThreadPoolExecutor.runWorker: 1167

ThreadPoolExecutor$Worker.run:

Thread.run 919 .*

**Link(s) to mod(s) used**: `[]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Slotterleet** [comment] 2022-12-18 08:24
Duplicate of #8066. Provide freaking details. Also, check your internet connection, just in case.

**Comment by Slotterleet** [comment] 2022-12-18 08:26
The mod browser works for 99.9% of the people (including me), so it must be the issue on your end.
![Screenshot_20221218_112532_io anuke mindustry](https://user-images.githubusercontent.com/62336673/208288527-2e3772a6-bab7-4af8-b055-a33b1de1450b.jpg)

**Comment by buthed010203** [comment] 2022-12-18 15:16
Once again we cannot do anything about it unless you provide the error log

**Closed** 2023-01-07 17:09 UTC
