### ISSUE TITLE
iPhone 11 touch screen not working

### ISSUE THREAD

**Issue by Univ3rse01** [Anuken/Mindustry#4226] opened 2021-01-02 04:37 UTC
**Platform**: `iOS x32`

**Build**: `release build 122.2`

**Issue**: *Touch screen doesn’t work only on the top of the screen

**Link(s) to mod(s) used**: `[genNAowl/upgraded-factories:1.0]`

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GlennFolker** [comment] 2021-01-02 04:49
Thank you for not filling the checkboxes

**Comment by joshuaptfan** [comment] 2021-01-02 04:59
#4197 #4199 #4205 #4215 #4216 #4217 #4219 #4220 #4221 #4223 #4224

**Comment by DeltaNedas** [comment] 2021-01-02 05:06
are all ios players like this

**Comment by itcannotbe** [comment] 2021-01-02 08:09
> are all ios players like this

Apparently yes. 'cause they didn't pay for the app. Their parents did.

**Comment by itcannotbe** [comment] 2021-01-02 08:12
Duplicate of #4197 #4199 #4205 #4215 #4216 #4217 #4219 #4220 #4221 #4223 #4224 #4228

**Comment by DeltaNedas** [comment] 2021-01-02 10:17
\>duplicate of issue from the future

**Comment by markozajc** [comment] 2021-01-02 10:37
blame steve jobs for having a trash deployment workflow

**Closed** 2021-01-02 15:43 UTC
