### ISSUE TITLE
Strange sounds, even with no volume

### ISSUE THREAD

**Issue by SpeedofDeath118** [Anuken/Mindustry#1703] opened 2020-03-13 16:16 UTC
Android, Redmi 4A

Build 104.5

My phone was on zero volume and on Do Not Disturb but my phone made a few robot-like beeping sounds.

I'm not exactly sure how to reproduce it - it seemed slightly random. I was on a Mindustry.io server, in a high-stress situation (FPS was about 10, weapons fire everywhere).

**Comment by Anuken** [comment] 2020-03-13 16:42
If your phone is making sounds even when the system is at zero volume, that's an Android bug - no application should be able to output sound in that situation. Either way, I can't reproduce this on any of my 3 devices, so this won't be fixed.

**Closed by Anuken** 2020-03-13 16:42 UTC
