### ISSUE TITLE
Map file broken when playing multiplayer editor

### ISSUE THREAD

**Issue by Kieaer** [Anuken/Mindustry#1400] opened 2020-01-19 22:05 UTC
**Platform**: Windows

**Build**: Build 102.2

**Issue**: Map file broken when playing multiplayer editor.

**Steps to reproduce**: 
1. Open In-game editor
2. Open server
3. invite any players and build long time
4. map save and exit
5. map load
6. You can see this error
![캡처](https://user-images.githubusercontent.com/44261958/72689272-16427580-3b53-11ea-907d-25415c426002.PNG)

It's 100% bug.

**Comment by Anuken** [comment] 2020-01-19 23:06
This works for me; maps edited in multiplayer load correctly. I'll need some more specific reproduction steps than that.

**Comment by Kieaer** [comment] 2020-01-20 01:07
![1](https://user-images.githubusercontent.com/44261958/72691941-624de400-3b6c-11ea-9751-920b0d9eb00c.PNG)
More stacktrace

The block does not appear when other players build it.
Blocks are displayed only when the screen is moved or blocks are place/break.

It then generates this error randomly.

**Comment by Anuken** [comment] 2020-01-20 02:08
![image](https://user-images.githubusercontent.com/10100000/72693665-cc7c6f80-3aff-11ea-9a25-0771a27140d3.png)

I don't have that problem. Blocks appear immediately when either person builds something.

**Comment by Kieaer** [comment] 2020-01-20 06:03
after 6 hours I'll upload how to reproduce video to discord

**Comment by DeltaNedas** [comment] 2020-01-20 07:38
woo #1400

**Comment by Kieaer** [comment] 2020-01-20 13:28
Perhaps I need to create a map for more than six hours to reproduce this bug.
It doesn't occur in a short time.

**Comment by Kieaer** [comment] 2020-03-02 03:29
![1583119686092](https://user-images.githubusercontent.com/44261958/75643136-63048a80-5c81-11ea-8cdb-43c42a16b4cd.jpg)
![1583119703224](https://user-images.githubusercontent.com/44261958/75643144-6730a800-5c81-11ea-9e2e-a669ec36d7c6.jpg)
![1583119689177](https://user-images.githubusercontent.com/44261958/75643152-6dbf1f80-5c81-11ea-9e33-a7c6166de23f.png)
@Anuken Perhaps this is expected to be creating an error.

**Comment by Anuken** [comment] 2020-03-02 03:41
I still don't know what causes that or how to reproduce it.

**Comment by Kieaer** [comment] 2020-03-02 08:35
@Anuken 4 players, 300 x 300 map size, total 5 hours

**Comment by Anuken** [comment] 2020-03-02 15:39
Yeah I can't reproduce any issues with this at all. Setting the time to 5 hours in the future, or even simulating the main loop of the game to reflect 5 hours passing doesn't do anything. Both the host and client can still place and remove blocks correctly.

**Comment by Kieaer** [comment] 2020-03-03 13:08
It's random.. see this video
https://vimeo.com/395173393

**Comment by Kieaer** [comment] 2020-03-08 00:31
![may](https://user-images.githubusercontent.com/44261958/76154425-7602d900-611f-11ea-9141-453877ffa3ad.gif)
This may be the cause.

**Comment by Anuken** [comment] 2020-03-08 03:58
Does messing with nodes in that way cause map errors/block placement issues? By itself, it shouldn't be a problem - that happens because the power graph updates when you remove nodes.

**Comment by Kieaer** [comment] 2020-03-25 11:53
I am trying to reproduce the bug again.

**Comment by Kieaer** [comment] 2020-04-20 01:04
our players are afraid that this bug will be reproduced, so they don't want to do it :eyes: 

Maybe it will be fixed in 6.0.

**Comment by BlueWolfGaming** [comment] 2020-04-29 14:04
@Kieaer build 102.2? im pretttttttttttttttttttttttty sure its 104.10 you should be reporting about, 102.2 is quite outdated.

**Comment by BlueWolfGaming** [comment] 2020-04-29 14:05
As far as i know, with much experience with the Nydus server and countless hours on Editor, there has never been that error

**Comment by Kieaer** [comment] 2020-05-01 07:43
@BlueWolfGaming Last test version is 104.10

**Comment by BlueWolfGaming** [comment] 2020-05-01 08:41
From what I see, your client might have issues saving the map file, or your connection is full of jank.

**Comment by Kieaer** [comment] 2020-05-03 03:09
@BlueWolfGaming Not only am I, but other users have also experienced this bug

**Comment by Kieaer** [comment] 2020-05-09 02:41
@Anuken Bug reproduced
![ezgif com-optimize](https://user-images.githubusercontent.com/44261958/81461884-c367f900-91e9-11ea-87d5-dcceb9f13eed.gif)
![녹화_2020_05_09_11_32_11_30](https://user-images.githubusercontent.com/44261958/81461766-06759c80-91e9-11ea-8d19-ba6ec6917146.gif)
![녹화_2020_05_09_11_32_53_71](https://user-images.githubusercontent.com/44261958/81461769-09708d00-91e9-11ea-8c4e-dd7bfdf5d9d6.gif)

\+ When players connected to the editor server connect to the server again, the player list is said to be duplicated.

**Comment by Anuken** [comment] 2020-05-09 02:54
That's pretty wild. It could be related to the block change notification system, or the way entities are queued... but both of those things were rewritten in 6.0, so it's hard to debug or reason about. It could have fixed this issue altogether.

**Comment by Anuken** [comment] 2020-07-28 01:07
I'm going to close this, at least for now:
- It's not clear what causes it
- I haven't been able to reproduce despite trying multiple times
- v6 has many changes to core entity logic, and it's not clear whether or not this issue will still occur
- There's not much to discuss unless it happens in a newer version again

I'll reopen this if anything new happens.

**Closed by Anuken** 2020-07-28 01:07 UTC
