### ISSUE TITLE
plastanium walls don't properly block automatic power connections

### ISSUE THREAD

**Issue by Dude-324** [Anuken/Mindustry#4954] opened 2021-03-18 02:45 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*
win 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
126.1
**Issue**: *Explain your issue in detail.*
plastanium walls only block automatic node connections when the node is placed after something else(airblasts, factories, generators), but they don't block connections when the node is placed after the block
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
i found the issue while making a schematic, and afterwards to make sure it really was the issue i placed down a power node entirely surrounded with plastanium walls and tried placing drills, factories, batteries, generators and the like outside the plastanium walls. the node connected through the plastanium walls. this also happened with the large power node, surge tower and power source, as well as through several layers of plastanium walls
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
i used no mods
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[plast wall bug save.zip](https://github.com/Anuken/Mindustry/files/6160946/plast.wall.bug.save.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Dude-324** [comment] 2021-03-18 02:48
i'm not certain i understood exactly what the line about saves meant, and i didn't see it in multiplayer but i think it happens in multiplayer as well. the save i attached is the custom game i found and tested the bug in

i also did look through all the open pull requests but i didnt look through all the over 2k closed ones

**Comment by joshuaptfan** [comment] 2021-03-18 03:17
I don't know what commit fixed it, but I encountered this bug yesterday, and could not reproduce it in the latest bleeding edge build, so it doesn't exist anymore.

**Comment by Quezler** [comment] 2021-03-18 09:08
> It was probably fixed in this commit.

correct, it kinda got discussed in the private development channel on discord, and this was one of the resulting commits ^

**Comment by RandomTNT** [comment] 2021-03-18 09:11
As it was fixed, close it

**Closed** 2021-03-18 13:03 UTC
Labels: bug
