### ISSUE TITLE
Multiplayer bug

### ISSUE THREAD

**Issue by Biggocl123** [Anuken/Mindustry#1531] opened 2020-02-08 05:18 UTC
Platform:Android

Build : 103.4

Issue : in multiplayer at random times (mostly near a enemy's base) I will die without any warning,shot, or sound.

Steps to reproduce : randomly in multiplayer;mostly in laggy servers.

**Comment by Anuken** [comment] 2020-02-08 05:21
Probably caused by clusters of turrets or enemies reacting slower clientside and killing the player before they notice. Won't fix.

**Closed by Anuken** 2020-02-08 05:21 UTC

**Comment by indielm** [comment] 2020-02-08 05:33
use /sync 
frequently
you likely were desynced from seeing the bullets
