### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by Jeamorg** [Anuken/Mindustry#9437] opened 2024-01-07 11:23 UTC
### Platforms

Windows

### Build

release build 146

### Issue

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: release build 146
OS: Windows 10 x64 (amd64)
Java Version: 16.0.1
Runtime Available Memory: 4080mb
Cores: 6
Mods: none (vanilla)

java.lang.NullPointerException: Cannot read field "size" because "this.plans" is null
	at mindustry.gen.UnitEntity.isBuilding(UnitEntity.java:560)
	at mindustry.gen.UnitEntity.clipSize(UnitEntity.java:699)
	at mindustry.entities.EntityGroup.draw(EntityGroup.java:113)
	at mindustry.core.Renderer.draw(Renderer.java:379)
	at mindustry.core.Renderer.update(Renderer.java:231)
	at arc.ApplicationCore.update(ApplicationCore.java:37)
	at mindustry.ClientLauncher.update(ClientLauncher.java:237)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:204)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:192)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:54)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:39)

### Steps to reproduce

When I entered the community server and played for less than a minute, the game crashed. It didn’t crash when I played before.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment] 2024-01-07 13:47
This has been reported before, but needs specific reproduction steps. It is not a crash that can be fixed without consistent steps to reproduce, and may be caused by a malfunctioning plugin/server.

**Closed by Anuken** 2024-01-07 13:47 UTC
Labels: bug
