### ISSUE TITLE
Grass looks gray in editor select screen

### ISSUE THREAD

**Issue by Excavator987** [Anuken/Mindustry#2605] opened 2020-09-19 07:38 UTC
**Platform**: Windows

**Build**: 9796

**Issue**: Grass looks gray in editor select screen

**Steps to reproduce**: Have a map with grass in it, and press Editor when you open the game
![image](https://user-images.githubusercontent.com/58992170/93661891-6ad82080-fa53-11ea-9983-96bc1fe67854.png)
![image](https://user-images.githubusercontent.com/58992170/93661914-880cef00-fa53-11ea-8e80-7045452e9284.png)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment] 2020-09-19 07:41
duplicate of #2593 (though the issue itself is valid since apparently it wasn't fixed according to your build number ^)

**Comment by Quezler** [comment] 2020-09-19 07:44
could not replicate in `9796`, are you sure that is the number under the logo?

![Screen Shot 2020-09-19 at 09 43 51](https://user-images.githubusercontent.com/3179271/93661997-a75c4a00-fa5c-11ea-8154-21bfa0cbcd7e.png)

**Comment by Excavator987** [comment] 2020-09-19 08:15
the issue is still apparent though - if no one reports it, it won't be fixed anytime soon

**Comment by Excavator987** [comment] 2020-09-19 08:16
so I wouldn't see it as a duplicate, since the report you gave does not mention about editor

**Comment by Anuken** [comment] 2020-09-19 16:15
Caused by an outdated preview or an old version, clear your data.

**Closed by Anuken** 2020-09-19 16:15 UTC
Labels: bug
