### ISSUE TITLE
Power doesn't work in PVP for non-host

### ISSUE THREAD

**Issue by bencbartlett** [Anuken/Mindustry#893] opened 2019-10-26 08:01 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows, Steam

**Build**: *The build number under the title in the main menu. Required.*

98.1

**Issue**: *Explain your issue in detail.*

When creating a PVP game on the Veins map (possibly other maps), players who are not the host are unable to use power. Placing power poles doesn't connect to any of the structures.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*

Tried PVP with a friend for the first time and discovered this bug after 20 minutes when he tried to make silicon. Save file is attached. 

[mindustry_bug.zip](https://github.com/Anuken/Mindustry/files/3774582/mindustry_bug.zip)

**Comment by Quezler** [comment] 2019-10-26 08:43
Probably has something to do with that the [placing](https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/world/blocks/power/PowerNode.java#L102) of the powernode is only ran for the server, which is in a different team presumably 🤔 
(which also explains why the configuration gui does work, it [does not](https://github.com/Anuken/Mindustry/blob/master/core/src/io/anuke/mindustry/world/blocks/power/PowerNode.java#L161) have said check 😗)

**Comment by Anuken** [comment] 2019-10-26 12:10
The issue is, connecting nodes works fine for me on multiplayer. I've tested it several times ok several devices. Yes, the node connection code doesn't run on the client, but `Tile#configure` is synced across clients.

**Comment by Quezler** [comment] 2019-10-26 12:18
@anuken are you sure your server was set to pvp? 😗 (the on-place auto configuration that is)

**Comment by Quezler** [comment] 2019-10-26 12:29
@Anuken 

`Tile#configure` is only ran by the server, which ends up in `Call.onTileConfig(player, this, value)`, notice the current player (aka: server/host) being sent along which eventually ends up in `!Units.canInteract(player, tile))` which ends up doing the team check, and since the player sent along is on a different team the automatic connection(s) fail 😚

**Comment by Anuken** [comment] 2019-10-26 12:57
Should be fixed now.

**Closed by Anuken** 2019-10-26 12:57 UTC
