### ISSUE TITLE
About assets' license

### ISSUE THREAD

**Issue by codehz** [Anuken/Mindustry#137] opened 2018-07-07 14:35 UTC
The repo was pushed currently with the GPLv3 license in a LICENSE.md file. Typically the GPLv3 is used for code. It;s good but I think we need an asset-specific license (typically Creative Commons), and a list of names of all artists who worked on those assets for attribution.

The assets would be anything that is not code: textures, music, fonts, etc. I don't know a priori of any incompatibility to use the GPL license to cover the assets, but as it's written as a code-specific license, I believe it would be better to use a Creative Commons license (e.g. CC BY 4.0 or CC BY-SA 4.0).

**Comment by Anuken** [comment] 2018-07-07 20:00
Now is a bad time to add a license, as I am planning to re-draw all the sprites and fonts to myself, and, if possible, re-make the music and sounds, thus not using any external assets [besides the Korean/Chinese fonts].

In the future, I'll probably use CC BY-NC 3.0 for the assets.

**Comment by sparr** [comment] 2018-12-12 00:08
Suggest dual license, CC-BY-NC and CC-BY-SA? That is, allow commercial usage iff that usage is also CC-BY-SA licensed.

**Comment by GithubSuckBigTime** [comment] 2019-01-21 16:45
GPL is sometimes used for assets as well, there are games that do it, and e.g. [OpenGameArt](https://opengameart.org/) allows it as well, but Creative Commons is usually better. Anyway, you could dual license them uder GPL and CC.

> CC-BY-NC

Watch out here! This is **not a free license** ([a small cheatsheet](https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Creative_commons_license_spectrum.svg/2000px-Creative_commons_license_spectrum.svg.png)). The NC (and also ND) clause breaks the definition of free cultural works, and is [very much discouraged](https://freedomdefined.org/Licenses/NC). Please take a moment to read the linked material, it explains why NC is a problem and why it is mostly unnecessary as well. With such license the game could no longer be considered free/open source, and would have to be removed from [libregamewiki](https://libregamewiki.org/Mindustry).

I would strongly suggest CC-BY-SA, as most libre games do (e.g. 0 A.D., Ryzom, Xonotic, SuperTuxKart, ...). That is a free license that offers enough protection against abuse.

**Comment by Anuken** [comment] 2019-01-21 22:52
> but Creative Commons is usually better

Could you explain why this is the case? Is it really worth adding another license just for assets?

**Comment by GithubSuckBigTime** [comment] 2019-01-22 04:15
As @codehz says, GPL was designed for code, and it is mostly used for code. Similarly CC were designed for art works and are mostly used in that way. So, while it is possible to have everything under GPL, with CC you **support reuse of your assets**. Other artists who use CC licenses can simply "drop-in" your work, add you to the credits and that's it. With GPL they can reuse the assets as well, but they'll have to have their work under multiple licenses with different terms, and that can be discouraging and cause friction. (As the [FSF states](https://www.gnu.org/licenses/license-list.html#ccbysa), CC-BY-SA can be relicensed to GPL, but not the other way around.)

Now if you ask me personally, this is really worth doing with games that have a considerable amount of generally reusable assets that are likely to be reused and shared elsewhere (e.g. [Ryzom Commons](https://atys.wiki.ryzom.com/wiki/Category:Ryzom_assets)). Mindustry doesn't seem like this case, there is good art, but it is quite minimal and specific to the game, and there are a lot of minimal pixel art resources e.g. on OpenGameArt under more convenient licenses (CC0), for those who are looking for such assets. So I would be okay with keeping this whole, including assets, under the GPL, for simplicity. E.g. [Blackvoxel](https://www.blackvoxel.com/view.php?node=1239) does it the same (see the license section). But in this case, please explicitly say in the README that you intend to apply the GPL to assets too, to prevent confusion.

On the other hand you could very simply dual license the assets under GPL and CC-BY-SA for convenience -- that is you would say "this game is GPL as a whole, but if you want just the assets, you can choose CC-BY-SA as well". This could be done with just adding a single paragraph to the README.

**Comment by Anuken** [comment] 2019-01-22 15:03
> it is quite minimal and specific to the game

This may be further compounded by the fact that, as of the latest version, Mindustry's sprites are automatically scaled and antialiased from the pixel art images. The 'real' versions of the sprites are not included in the repository, as they need to be auto-generated. Maps are similarly auto-generated and very specific to Mindustry; I don't see them being useful anywhere else.

For now, I think it would be best to keep everything as GPL and change it if (as you said) there is significant demand for specific assets.

**Comment by GithubSuckBigTime** [comment] 2019-01-23 06:52
Yes, I really think keeping the same terms for the whole repository will help keep the attention on simply moving the game forward in this situation. The question of more complex licensing can come up when the art section becomes a subproject of its own, with its own team, rules etc.

Let's just add that this:

> list of names of all artists who worked on those assets for attribution.

can be done regardless of license and I think it's always a good idea, even if credit is not required. When the project grows, it's good and useful to know all contributors (e.g. like [this](https://github.com/OpenMW/openmw/blob/master/AUTHORS.md)), for many reasons (legal, practical, moral, ...).

**Comment by Famous5000** [comment] 2019-04-15 16:56
And the other problem could be with the other licenses that people can't play the game on YouTube without fear of getting a copyright strike. CC fixes that.

**Comment by Arkanic** [comment] 2019-06-14 19:00
@Famous5000, agreed. I think that youtube, at the moment, is one of the main ways that the public can find out about the game.
maybe even starting an official channel?

**Comment by Anuken** [comment] 2019-07-04 04:11
I think it's safe to close this now. The assets are going to be staying as GPL, while:
> list of names of all artists who worked on those assets for attribution.

...is not going to be necessary, since all the assets are now made by me *(with the exception of the fonts, which I obtained from Google Fonts and whose authors I have lost at this point)*.

**Closed by Anuken** 2019-07-04 04:11 UTC

**Comment by oong819** [comment] 2024-09-11 02:23
> > it is quite minimal and specific to the game
> 
> This may be further compounded by the fact that, as of the latest version, Mindustry's sprites are automatically scaled and antialiased from the pixel art images. The 'real' versions of the sprites are not included in the repository, as they need to be auto-generated. Maps are similarly auto-generated and very specific to Mindustry; **I don't see them being useful anywhere else.**
> 
> For now, I think it would be best to keep everything as GPL and change it if (as you said) there is significant demand for specific assets.

I would want to use launch.ogg for my CC-BY-SA animation, and GPL require the full license included while Section 3(a)(1)(c) of CC-BY-SA 4.0 International states that 

> c. indicate the Licensed Material is licensed under this
               Public License, and include the text of, or the URI or
               hyperlink to, this Public License.

So yeah CC-BY-SA is much more convenient, with GPL i would have to include the whole GPL license in my anination
