### ISSUE TITLE
Eternal Burning Core bug

### ISSUE THREAD

**Issue by Juja-Gaf** [Anuken/Mindustry#3095] opened 2020-10-24 19:35 UTC
**Platform**: Windows

**Build**: Mindustry [BETA] build 109

**Issue**: When I lose on the map (Nuclear Production Complex), the bots, destroying my core, set it on fire abundantly, but now when I return to this map, the core that spawns continues to burn and is destroyed by itself.

**Steps to reproduce**: I started to go through the map (Nuclear production complex) and lost on boss 41 Waves. Ground bots destroyed my core, simultaneously setting it on fire. After I again recruited resources and booted to this zone, my kernel was already on fire, and itself destroyed within +- 30 seconds. This was followed by several more attempts to download, the result was the same
I even tried to extinguish the core by spilling water under it)) I was building a Power Projector and a repair projector, the maximum of which I achieved, there was a more or less stable combustion of the core .. But at the same time, the conveyors that I bring to it burn out ...
By itself, this fire does not go out.
Help me please)
(P.S. All the text was translated through google-translator, so you should enclose it :3)

**Link(s) to mod(s) used**: I have not used any mods.

**Save file**: https://drive.google.com/drive/folders/1A3adDUq_TbnaF1cNqt1ot1qrbWAnbLA2?usp=sharing

**Crash report**: I cannot figure out how to retrieve a bug report, please find it yourself in the attached file.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by YellOw139** [comment] 2020-10-24 19:46
Dunno if it's really a bug. Happened to me too today. See #development on Discord (just see; it's been discussed and any further messages from me or someone else are apparently seen as annoying).

The issue is that if you have flammable materials in your core, when the core catches the old fire (which would've well burned off by the time you launch the second core) gets realimented by the flammables in your new core and continues burning.

Dunno if it's a bug, but even if it wasn't, I'm not sure it's an intended gameplay mechanic that players will understand either.

**Comment by QmelZ** [comment] 2020-10-24 19:50
actually fixed by the new "clear campaign saves" option in the game data settings.

**Closed** 2020-10-24 19:55 UTC
Labels: bug
