### ISSUE TITLE
Vanishing units

### ISSUE THREAD

**Issue by Somka000** [Anuken/Mindustry#4686] opened 2021-02-15 15:48 UTC
**Platform**: *Linux*

**Build**: *124.1 server build*

**Issue**: *All units despawn 5-30 seconds after being created, there has never been a bug like this on server. I load save to singleplayer and all new units despawn too. All logic see units. I dont see problem when game was started (1-15 wave). Sync, rejoin and server restart dont fix it. I dont use js.
![mono](https://user-images.githubusercontent.com/51973243/107966746-92a0c580-6fac-11eb-99df-9332a2b1c40d.png)
![monos](https://user-images.githubusercontent.com/51973243/107966783-9df3f100-6fac-11eb-90bf-3cbfed40df8c.png)

*

**Steps to reproduce**: *This is a normal survival game on Mud Flats.*

**Save file**: *[4.zip](https://github.com/Anuken/Mindustry/files/5982461/4.zip)
*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by TranquillyUnpleasant** [comment] 2021-02-15 15:50
Duplicate of #4685 and has been fixed.

**Closed** 2021-02-15 15:58 UTC
Labels: bug
