### ISSUE TITLE
Daggers don't shoot or aim properly at specific wall placement

### ISSUE THREAD

**Issue by LeoSko** [Anuken/Mindustry#5255] opened 2021-05-17 04:44 UTC
**Platform**: Windows/Linux server

**Build**: 126.2 or BE 21068

**Issue**: When there is a specific placement of walls (or, in fact, other structures), daggers aim in the wrong direction and don't shoot anywhere. Even when they do after getting closer, their bullets don't reach the target (see till 5 of them stack up in the gif below) making them not to progress.

**Steps to reproduce**: use attached map, see gif:
![dagger_ai](https://user-images.githubusercontent.com/4199082/118433171-115bea80-b6e3-11eb-9869-5dd12ed05bda.gif)

**Link(s) to mod(s) used**: no mods

**Save file**: 
[dagger_test.zip](https://github.com/Anuken/Mindustry/files/6491130/dagger_test.zip)

**(Crash) logs**: Not a crash

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by BlueWolf3682** [comment] 2021-05-17 07:19
This is caused by the same thing as https://github.com/Anuken/Mindustry/issues/5254. 
For some reason units' range of firing and range of targeting are different.

**Comment by Anuken** [comment] 2021-05-17 14:25
Fixed in 7.0.

**Closed by Anuken** 2021-05-17 14:25 UTC
Labels: bug
