### ISSUE TITLE
UI is covered on iPhone XR

### ISSUE THREAD

**Issue by Terio9** [Anuken/Mindustry#3749] opened 2020-12-03 18:17 UTC
Platform: iOS

Build: idk, newest version from AppStore, 6.0?

Issue: UI is covered by rounded corners and notch.

Steps to reproduce: Just run an app on iPhone X and up...

Link(s) to mod(s) used: No mods used.

Save file: Not needed.

(Crash) logs: Game does not crash

**Comment by itcannotbe** [comment] 2020-12-03 18:19
Duplicate of # TOO MANY TO MENTION ALREADY.

**Comment by Terio9** [comment] 2020-12-03 18:20
Idk what is going on with this game. Refunded.

**Closed** 2020-12-03 18:46 UTC
Labels: bug

**Comment by willis936** [comment] 2020-12-03 20:46
https://github.com/Anuken/Mindustry/issues/3719
