### ISSUE TITLE
Sandbox saves becoming survival saves

### ISSUE THREAD

**Issue by ifritdiezel** [Anuken/Mindustry#2357] opened 2020-08-15 17:37 UTC
**Platform**: **Linux**

**Build**: **BE 9289** and below

**Issue**: Sandbox mode save randomly becomes a survival mode save (infinite resources and wave skip disappear) when loaded. It happened multiple times on different maps.

**Steps to reproduce**:  Create a sandbox save, load it, use save and quit, load it again. 

---
*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-08-15 19:16
This has never happened to me, or, as far as I know, anyone else. I load up many different types of sandbox saves several times every day.

Unless someone else has clear steps to reproduce this issue, it won't be fixed.

**Closed by Anuken** 2020-08-15 19:16 UTC
Labels: bug

**Comment by iMplode-nZ** [comment] 2020-08-16 04:04
I have had this, but only due to my computer shutting down in the middle of the game.

**Comment by Eldoofus** [comment] 2020-08-18 14:20
It happened to me on multiple occasions
