### ISSUE TITLE
Mono AI decision making problem(s?)

### ISSUE THREAD

**Issue by Larofeticus** [Anuken/Mindustry#9392] opened 2023-12-17 20:14 UTC
### Platforms

Windows

### Build

146

### Issue

Operating monos on a map where the nearest copper and lead are ~200 tiles away. Instead of balancing between lead and copper, the monos only mine copper.

At ore overlay distance 100, the problem still occurs, but If the nearest ore is 99 tiles away, then the monos choose mining targets as expected.

Additionally, I found that around that 99/100 distance, if I cover up ore overlays, the monos can become completely idle; they will either wait for the ore to be uncovered and resume mining, or they emerge from the factory and never go anywhere or do anything.

### Steps to reproduce

Make a map where the ore/lead is >99 tiles away from the core, then release some monos.

cover up the ores with buildings to further confuse them, sometimes to the point of permanently locking them motionless, even though other ore tiles are available to mine at.

Some reference video is available here: https://youtu.be/U60sZfg3waM?si=aKxPvHVFJitjPTWn&t=868

### Mods used

None.

### Save file

[mono_ai_bugs.msav.txt](https://github.com/Anuken/Mindustry/files/13697639/mono_ai_bugs.msav.txt)

Github complaining that it doesn't support .msav file format so I added a .txt extension.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment] 2023-12-17 21:36
Pretty sure this is a duplicate of #8917, which was fixed after release.

**Closed by Anuken** 2023-12-17 21:36 UTC
Labels: bug
