### ISSUE TITLE
Conveyor corners shake

### ISSUE THREAD

**Issue by Esnardo** [Anuken/Mindustry#2600] opened 2020-09-19 01:39 UTC
**Platform**: *Android*

**Build**: *9748*

**Issue**: *Any gray conveyor that isn't straight or a ↵←merge will noticably shake. [Video (look at the corners of the conveyor)](https://github.com/Anuken/Mindustry/files/5248924/Why.do.i.have.to.zip.this.zip)*

**Steps to reproduce**: *Place a conveyor that isn't straight. I think this probably has something to do with my device, which is an amazon fire HD8*

**Link(s) to mod(s) used**: *None*

**Save file**: *I mean do you really need one? just place some conveyors. It works on every save file I've tested*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Esnardo** [comment] 2020-09-19 01:42
Shit sorry build is 9748

**Comment by sk7725** [comment] 2020-09-19 02:13
h

**Comment by Anuken** [comment] 2020-09-19 02:26
This is (probably) caused by the 4K texture atlas size and limited shader precision on mobile. Won't be fixed anytime soon, if at all.

**Closed by Anuken** 2020-09-19 02:26 UTC
Labels: bug
