### ISSUE TITLE
Controlling payload and picking up units using logic in multiplayer causes client side players to crash

### ISSUE THREAD

**Issue by GenericSomeone** [Anuken/Mindustry#5275] opened 2021-05-20 01:37 UTC
**Platform**: *Linux*

**Build**: *126.2*

**Issue**: *Controlling payload and picking up units using logic in multiplayer causes client side players to crash*

**Steps to reproduce**: *This bug is present on all payload units commanded by logic, but using megas is the easiest way to replicate it.*

*Log in to any server as a client, and place the schematic given in the save file below. Enter the arc in the schematic and command a sizable group of megas (during testing, 70 or so were found to be effective at replicating the bug). Fly the megas over to a group of ground units that are small enough for a mega to pick up, and hover over them. At this point, the logic should start commanding the megas to pick up the units, and subsequently trigger the crash.*

*If this fails to reproduce the crash, shoot the arc to command the megas to drop the units, and pick them up again. Doing this repeatedly should replicate the crash reliably.*

*Interestingly enough, this behavior is not seen in singleplayer. During an LAN game, the host doing the above will not cause the host to crash, but may result in other connected players crashing instead.*

**Link(s) to mod(s) used**: *No content mods were used; however, several testing mods were used to help replicate the bug, which may or may not affect the debugging process.*

https://github.com/MEEPofFaith/testing-utilities

https://github.com/DeltaNedas/ui-lib

https://github.com/DeltaNedas/unit-factory

**Save file**: *

*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

(please note: The bug was replicated with a LAN game, although the bug should occur as normal on any server. The save file is the server side save file. The crash log was taken from the client computer.)

**(Crash) logs**: *
[crash-report-05_19_2021_17_24_27.txt](https://github.com/Anuken/Mindustry/files/6512285/crash-report-05_19_2021_17_24_27.txt)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GenericSomeone** [comment] 2021-05-20 01:39
Odd, for some reason the save file failed to upload, please stand by

**Comment by GenericSomeone** [comment] 2021-05-20 01:46
This should be the save
/home/a/Downloads/Games/mindustryV6/bug.zip

**Comment by Anuken** [comment] 2021-05-20 01:50
Duplicate of #4882

**Closed by Anuken** 2021-05-20 01:50 UTC
Labels: bug
