### ISSUE TITLE
Not connecting with mod

### ISSUE THREAD

**Issue by scoennz** [Anuken/Mindustry#913] opened 2019-10-27 18:46 UTC
Windows 10
Build 98.1

I created an edited version of Veins with silver my friend managed to connect to the LAN perfectly. When I add golden sand he can't connect. I don't remember the exact error message but it was something about something not being able to cast to something else.

**Comment by Anuken** [comment] 2019-10-27 18:52
Duplicate of #873

**Closed by Anuken** 2019-10-27 18:52 UTC
