### ISSUE TITLE
Mindustry has crashed 

### ISSUE THREAD

**Issue by LegendaryPeddler5550** [Anuken/Mindustry#5071] opened 2021-04-06 21:56 UTC
Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: bleeding-edge build 21007
OS: Linux x32
Java Version: 0
Java Architecture: null
0 Mods

> ArcRuntime: 'arc.util.ArcRuntimeException: Error reading file: sprites/sprites.atlas (internal)'
AssetManager.handleTaskError: 670
AssetManager.update: 442
AssetManager.update: 465
ClientLauncher.update: 143
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1582
GLSurfaceView$GLThread.run: 1281
> ArcRuntime: 'Error reading file: sprites/sprites.atlas (internal)'
AndroidFi.read: 62
TextureAtlas$TextureAtlasData.<init>: 350
TextureAtlasLoader.getDependencies: 45
TextureAtlasLoader.getDependencies: 20
AssetLoadingTask.handleSyncLoader: 83
AssetLoadingTask.update: 72
AssetManager.updateTask: 591
AssetManager.update: 440
AssetManager.update: 465
ClientLauncher.update: 143
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1582
GLSurfaceView$GLThread.run: 1281
> FileNotFound: 'sprites/sprites.atlas'
AssetManager.nativeOpenAsset: -2
AssetManager.open: 902
AssetManager.open: 879
AndroidFi.read: 60
TextureAtlas$TextureAtlasData.<init>: 350
TextureAtlasLoader.getDependencies: 45
TextureAtlasLoader.getDependencies: 20
AssetLoadingTask.handleSyncLoader: 83
AssetLoadingTask.update: 72
AssetManager.updateTask: 591
AssetManager.update: 440
AssetManager.update: 465
ClientLauncher.update: 143
AndroidGraphics.onDrawFrame: 374
GLSurfaceView$GLThread.guardedRun: 1582
GLSurfaceView$GLThread.run: 1281

**Comment by Anuken** [comment] 2021-04-06 22:03
Can't reproduce, won't fix.

**Closed by Anuken** 2021-04-06 22:03 UTC
Labels: bug
