### ISSUE TITLE
I can't enter the game.

### ISSUE THREAD

**Issue by blool22** [Anuken/Mindustry#766] opened 2019-10-03 01:25 UTC
**Platform**: Windows 7

**Build**: I can't see it. (but I think it's the last one, I'm using steam)

**Issue**: I try to open the game and it opens with a black screen for a fraction of a second and then closes

**Steps to reproduce**: I just open the game

Here are some files that appeared in the game files when I try to open it

[hs_err_pid648.log](https://github.com/Anuken/Mindustry/files/3684080/hs_err_pid648.log)
[hs_err_pid1360.log](https://github.com/Anuken/Mindustry/files/3684081/hs_err_pid1360.log)
[hs_err_pid168.log](https://github.com/Anuken/Mindustry/files/3684082/hs_err_pid168.log)

**Comment by Anuken** [comment] 2019-10-03 01:37
Duplicate of https://github.com/Anuken/Mindustry/issues/710. You can't play the game, your computer doesn't support it.

**Closed by Anuken** 2019-10-03 01:37 UTC
