### ISSUE TITLE
Crash after being alt tabbed

### ISSUE THREAD

**Issue by Raotor123** [Anuken/Mindustry#17] opened 2017-12-12 23:40 UTC
The game crashed with this error after I alt tabbed and did something on my second screen.
![image](https://user-images.githubusercontent.com/25741824/33914390-3be7ec92-df9e-11e7-9613-20ba66baa546.png)
I could reproduce the error when resizing the window and moving the mouse around wildly, although this is not what I was doing when it first occurred.

**Comment by Anuken** [comment] 2017-12-13 18:28
I _think_ this is caused by fetching the screen size of the wrong monitor when constructing a framebuffer. Not sure how to test it, as I only have one monitor.

**Comment by Raotor123** [comment] 2017-12-13 20:27
I guess this was a 1 in a million occurrence, because it didn't happen again when i switchted focus to the other monitor. At least you know it's out there:).

**Comment by Anuken** [comment] 2017-12-14 20:41
_Might_ have been fixed by a Framebuffer creation change in 1acc47190c827932c03fd827a98152f45509fd4e. Will keep this issue open for a while longer just in case.

**Closed** 2018-01-18 23:18 UTC
