### ISSUE TITLE
Conveyor belt corners don't stop animating when the items stop moving

### ISSUE THREAD

**Issue by codiophile** [Anuken/Mindustry#1223] opened 2019-12-17 17:36 UTC
**Platform**: Android

**Build**: 101

**Issue**: I just noticed a very minor bug in the animation of conveyor belts. When the items on the belt stop moving, because the destination is full, the conveyor belt stops animating that it's moving. This is true except for corners, they never stop animating. It's a minor issue that I can live with, but would be nicer if the animation was consistent throughout the conveyor belt.

**Steps to reproduce**: Build a conveyor belt with a corner and a dead end and fill it with items. Notice how the animation stops once the items stop moving, except for in the corners, that keep animating.

**Comment by Anuken** [comment] 2019-12-17 18:14
Not a bug, as the conveyors technically still have space at the back for more items. This will not be changed unless the [conveyor optimization](https://github.com/Anuken/Mindustry/tree/conveyor-optimizations) branch is merged.

**Comment by codiophile** [comment] 2019-12-17 21:46
@Anuken I don't think anyone cares about that technicality. The items are not moving, so the conveyor belt shouldn't be moving. The fact that it could take another item if there was something connecting to it from the back is not really relevant, because there isn't.

It should be easy to check in code if a conveyor has something connecting to it from the back and if it doesn't, you could stop the animation at capacity - 1, instead of at capacity. I think it would look much better and be much more intuitive.

I can understand if you don't consider this a high priority bug, but I still think you should consider it a bug. It may be behaving as you expect it to, but I think the vast majority of users would expect it to stop animating, because the fact that it's a corner doesn't seem like it should matter. 

When do you expect to merge the conveyor optimisation and is there any chance you would reconsider this as a bug?

**Comment by Anuken** [comment] 2019-12-19 01:06
>

**Comment by Anuken** [comment] 2019-12-19 01:06
>

**Closed by Anuken** 2019-12-19 01:06 UTC

**Comment by Anuken** [comment] 2019-12-19 01:14
>  I don't think anyone cares about that technicality. 

*I* do. Yes, I realize that users expect it to stop animating, but the fact remains that the conveyor isn't full and the system doesn't consider it to be stopped. The flaw is in the conveyor system itself, which allows other "technicalities" like placing more than the supposed 3-4 items on a conveyor by inputting from the side or overlapping items very close to each other at conveyor boundaries. It's still "working as intended" as long as I stick to this system of conveyors.

I don't know when the conveyor rework/optimization will be merged, but when it is, most of these problems should be fixed. Until then, I won't be changing anything with the current system.

*(if you're wondering why I opened and closed this, I was using the mobile site and mistapped)*
