### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by V2lenta1n** [Anuken/Mindustry#9990] opened 2024-06-29 16:55 UTC
### Platforms

Windows

### Build

147

### Issue

After i buy & download official Minecraft, Mindustry doesn't launch

### Steps to reproduce

1.Buy Minecraft license;
2.Install Minecraft launcher;
3.Try to open Mindustry;
4.Mindustry doesn't launch.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by camelStyleUser** [comment] 2024-06-29 17:07
man got the 147 dev release
care to share?(real)

**Comment by Leo-MathGuy** [comment] 2024-06-29 18:58
Probably Java versions issue

**Comment by mahdoosh1** [comment] 2024-06-29 20:06
what is your java version?

**Comment by camelStyleUser** [comment] 2024-06-30 12:26
also thanks for paywalling the bug reproduction :smiling_face_with_three_hearts:

**Comment by TheCorruptedKing** [comment] 2024-06-30 12:54
This has to be either a typo or the biggest fucking joke in existence.

### **_Have you tried turning your PC off and on again_**

**Comment by kenos1** [comment] 2024-06-30 16:46
there is no way lmao

**Comment by V2lenta1n** [comment] 2024-07-01 13:21
> This has to be either a typo or the biggest fucking joke in existence.
> 
> ### **_Have you tried turning your PC off and on again_**

yes, but this dont help

**Comment by TheCorruptedKing** [comment] 2024-07-01 14:54
> yes, but this dont help

Try talking to Microsoft Support and see if you can request assistance on running mindustry on the Minecraft launcher :D👍

**Comment by Yarplay1** [comment] 2024-07-01 14:55
> > what is your java version?
> 
> my java is 21 version

maybe try using different java version? tho i have no idea why it breaks, mine works fine.

**Comment by kennarddh** [comment] 2024-07-01 14:55
> > what is your java version?
> 
> my java is 21 version

try 17

**Comment by Yarplay1** [comment] 2024-07-01 15:03
> > > what is your java version?
> > 
> > 
> > my java is 21 version
> 
> try 17

maybe 17 is wrong too. because this is a joke issue

**Comment by TG-TG-TG-TG-TG-TG** [comment] 2024-07-01 16:03
Minecraft 1.21 need java 21 and can't start with diffrent version if i remeber correct idk if mindustry want specific java version too

**Comment by Matita008** [comment] 2024-07-01 16:35
> > > what is your java version?
> > 
> > my java is 21 version
> 
> try 17

Iirc mindustry doesn't need java to run, since it's a compiled .exe file and not a .jar

**Comment by mahdoosh1** [comment] 2024-07-01 16:52
> > > > what is your java version?
> > > 
> > > my java is 21 version
> > 
> > try 17
> 
> Iirc mindustry doesn't need java to run, since it's a compiled .exe file and not a .jar

java doesnt compile to exe.
the exe file is used to execute the desktop.jar file in the `jre/` directory;

using the java version installed in `jre/bin` and `jre/lib` sub directory

**Comment by TheCorruptedKing** [comment] 2024-07-02 00:25
Would it be possible to see a receipt of which copy of Minecraft you bought in order to better assess how we can get your mindustry running?

**_Internally dying_**

**Comment by mahdoosh1** [comment] 2024-07-02 05:30
> > what is your java version?
> 
> my java is 21 version
> 

downgrade it to 17 or 16.

minecraft doesn't install java automatically (into os), minecraft has a jre in its data in `%AppData%/Roaming/minecraft/runtime`

unless the luncher needs it.

see if java 16 or java 17 works.

**Comment by Matita008** [comment] 2024-07-02 06:39
> > > > > what is your java version?
> > > > 
> > > > my java is 21 version
> > > 
> > > try 17
> > 
> > Iirc mindustry doesn't need java to run, since it's a compiled .exe file and not a .jar
> 
> java doesnt compile to exe.
> the exe file is used to execute the `desktop.jar` (actual game) file in the `jre/` directory;
> 
> using the java version installed in `jre/bin` and `jre/lib` sub directory.
> 
> but .exe file checks if java is installed if it is, uses the installed version in the os. if it is not, then it uses the one in `jre/bin`
> 
> if java version in the os isnt compatible, then it simply doesnt lunch

Does the .APK also contain the java VM?
If not, how does it run it?

**Comment by mahdoosh1** [comment] 2024-07-02 07:18
> Does the .APK also contain the java VM?
> If not, how does it run it?

No, java VM is already installed in phones. java is a cross platform language and most android apps are written in kotlin or java.

Android apps (.apk) are just zip files. in every apk file there are class files named classes.dex or classes2.dex

these are integrations of all compiled classes of the source code of the app. in this case Mindustry apk file has only `classes.dex`.

**Comment by Leo-MathGuy** [comment] 2024-07-02 07:20
> > > > > what is your java version?
> > > > 
> > > > 
> > > > my java is 21 version
> > > 
> > > 
> > > try 17
> > 
> > 
> > Iirc mindustry doesn't need java to run, since it's a compiled .exe file and not a .jar
> 
> java doesnt compile to exe. the exe file is used to execute the `desktop.jar` (actual game) file in the `jre/` directory;
> 
> using the java version installed in `jre/bin` and `jre/lib` sub directory.
> 
> but .exe file checks if java is installed if it is, uses the installed version in the os. if it is not, then it uses the one in `jre/bin`
> 
> if java version in the os isnt compatible, then it simply doesnt lunch

Thats the magic of java - its compiled to bytecode, which is run by the jvm. Only the jvm needs to be compiled separately for different devices, so everyone can run the same code. A .jar or .apk is just a zip file of .class files and other assets

**Comment by mahdoosh1** [comment] 2024-07-02 07:33
> 
> Thats the magic of java - its compiled to bytecode, which is run by the jvm. Only the jvm needs to be compiled separately for different devices, so everyone can run the same code. A .jar or .apk is just a zip file of .class files and other assets

were not supposed to explain java in the issue tracker.

and the author of this issue seems to be ignoring his issue and not playing mindustry anymore.

Anuke please close this issue.

**Closed** 2024-07-07 15:00 UTC
Labels: bug
