### ISSUE TITLE
Closing issues on Steam

### ISSUE THREAD

**Issue by CrowDev0** [Anuken/Mindustry#5821] opened 2021-08-20 19:19 UTC
**Platform**: Windows/Steam

**Build**: 126.3/130

**Issue**:
Everytime i try to close the game on Steam, is it because of a mod restart or i press quit or whatever, steam doesnt recognize the game being closed, and its nowhere in task manager, so i have to restart steam everytime i want to reload mods or just quit and come back to play later

**Steps to reproduce**:
Open the game on Steam. Usually it happens after i change something with mods, so try downloading or disabling/enabling a mod and restarting the game. After that, Steam thinks the game is still running and i have to restart

**Link(s) to mod(s) used**: (also happens without mods)

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by GamerMoment69** [comment] 2021-08-20 19:58
you sure this isn't a duplicate of #5146?

**Comment by Anuken** [comment] 2021-08-20 20:00
Same response as last issue - launching the game, installing a new mod and toggling a different mod does not prevent the game from closing correctly for me.

**Closed by Anuken** 2021-08-20 20:00 UTC
Labels: bug
