### ISSUE TITLE
sound bugs

### ISSUE THREAD

**Issue by daedaevibin** [Anuken/Mindustry#10314] opened 2024-11-07 18:02 UTC
### Platforms

Android

### Build

Version 7 official 146

### Issue

The error SoLoud: Failed to get output mix volume interface from SoLoud (the audio engine used in the game) suggests a low-level audio issue specific to this device's configuration or permissions. This error typically occurs when the audio library cannot access or control the device's primary audio interface for volume management, which is essential for playback control in applications, especially those using custom or modded audio.

Potential Causes:

- Device Compatibility: Some devices have limitations or unique configurations with OpenSL ES, which might not fully support certain audio features or interfaces. If the device has audio enhancements or restrictions (e.g., Dolby Atmos or other audio settings), disabling these temporarily might resolve the issue.

sys_app_log = created by phone

crash-log = created by Mindustry

[sys_app_log.txt](https://github.com/user-attachments/files/17667469/sys_app_log.txt)
[crash-log.txt](https://github.com/user-attachments/files/17667470/crash-log.txt)

(Forced to check some boxes, do not have time, nor ability to do all of them.)

### Steps to reproduce

Unknown. Randomly happened a few months ago, persists across roms and devices. (Galaxy A54, Pixel 6a)

### Mods used

Asthosus or any audio related/modifying mod created by Catser.

### Save file

Unobtainable.

### (Crash) logs

Already attached.

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Anuken** [comment] 2024-11-08 00:51
> Mods used
Asthosus or any audio related/modifying mod created by Catser.

I do not know what these mods do, and if they cause issues with the audio system, they should be fixed in the mod itself.

I cannot reproduce this in vanilla on my device, I did not create the audio library used, and I have no interest in fixing this.

**Closed by Anuken** 2024-11-08 00:51 UTC
Labels: bug
