### ISSUE TITLE
Double tapping core rebuilts destroyed blocks.

### ISSUE THREAD

**Issue by Positron832** [Anuken/Mindustry#2995] opened 2020-10-17 12:54 UTC
**Platform**: *Android 4.4.2.*

**Build**: *108.*

**Issue**: *Destroyed blocks get rebuilt when double tapping the core to respawn, it happens in any map, I was in sandbox mode.*

**Steps to reproduce**: *Open any map in sandbox mode, place combustion generators and fuel it with blast compound until they explode, then double tap the core to respawn.*

**Link(s) to mod(s) used**: *none.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

I only opened a map, I did not make a save file.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-10-17 13:16
> I only opened a map, I did not make a save file.

Doesn't matter. If you were playing in-game, I need a save file.

I can't reproduce this issue, and it seem to make any sense. Won't fix.

**Closed by Anuken** 2020-10-17 13:16 UTC
Labels: bug

**Comment by Positron832** [comment] 2020-10-17 18:01
Is it preferred to not comment after an issue is closed? Sorry if I am annoying right now.
[destroyedBlocksBug.zip](https://github.com/Anuken/Mindustry/files/5396212/destroyedBlocksBug.zip)
