### ISSUE TITLE
Multiple Cores Cause Weird Vault/Container Behaviour (Item Deletion!)

### ISSUE THREAD

**Issue by TastyGold** [Anuken/Mindustry#1417] opened 2020-01-22 04:48 UTC
Platform:
Mac

Build:
102.3

Issue:
If you have two or more cores in a mindustry word that both belong to you, adding surrounding vaults causes strange behaviour.
Size of the core is irrelevant. Adding a vault to one of the cores will increase the total storage by (1k * amount of present cores). Whenever any of the cores are updated, (eg: adding a vault, removing a vault, or being destroyed) the overall storage will be set accordingly. There are several ways to recreate this, each giving a variant of the glitch.

Steps to recreate:

Option 1-
Create a custom mindustry map with two cores.
Add a vault to one of the cores.
Notice the maximum storage increases by 2 thousand instead of 1.
Now surround the first core in vaults, the maximum storage will go up as if you did added vault to both.
This is the big problem:
Add a small container or vault to an un-expanded core. This will drop the maximum capacity a much lower value. You would essentially be back at step 2.
Another way to achieve this affect is to set fire to another core, not surrounded in vaults.
You can get the high storage back by simply updating the first one, that has the vaults around it. (Just delete and replace one)

Option 2- (Hurtful)
Play a multiplayer game with two cores each.
When you have lots of resources in vaults around one core, you could place a vault on your other core, and your resource supply would be cut in half. The same thing can happen when one of your cores is destroyed, your resource limit will be set to what it would be with your first core, but with no vaults. You will lose up to half of your resources.

This bug means that you can only vault up one core, as doing so adds enough storage that it equates to what would be with vaults on all of your cores. If you try to add vaults/containers to a second core, you will lose the extra resources in the vaults. Hope this helps. And thanks for reading if you do. If you aren’t anuke, please share this report with them.

**Comment by Anuken** [comment] 2020-01-22 05:00
Duplicate of #1401

**Closed by Anuken** 2020-01-22 05:00 UTC
