### ISSUE TITLE
Derelict repair in editor 

### ISSUE THREAD

**Issue by JasonP01** [Anuken/Mindustry#10170] opened 2024-09-02 18:07 UTC
### Platforms

Android

### Build

BE 25225 

### Issue

When edit in-game and you tap on a derelict block it repairs it, making dealing with derelict blocks in editor a nightmare to do

Has the side effect of changing every block in the game instantly cause everything is unlocked in editor.

It would be better if the interaction was only possible when the "rebuild" mode was on to repair stuff, so you dont repair stuff you might not want repaired

### Steps to reproduce

Place any derelict block and *accidentally* tap on it in edit in-game

### Mods used

Vanilla

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by broganeuquoixe** [comment] 2024-09-02 18:43
Not a bug, this is a suggestion https://github.com/Anuken/Mindustry-Suggestions/issues/new/choose

You need to change team from derelict to another to be even able to repair blocks. If you're in the editor and building derelict structures, how exactly are you going to accidentally repair stuff? You have to change team first.

Also, you can easily fix any "mistake clicks" just by using the team draw tools in the editor.

Please close this issue since it's not a bug

**Comment by JasonP01** [comment] 2024-09-02 18:56
@broganeuquoixe can you like stfu your opinion is not needed, your so goddamn annoying

**Comment by Matita008** [comment] 2024-09-03 05:24
> Not a bug, this is a suggestion https://github.com/Anuken/Mindustry-Suggestions/issues/new/choose

This is not the link to the suggestion

**Closed** 2024-09-03 17:43 UTC
Labels: bug

**Comment by JasonP01** [comment] 2024-09-03 19:03
@broganeuquoixe oh looky here, it got treated as a bug and fixed smartass

**Comment by Anuken** [comment] 2024-09-05 01:07
It's not really a bug (I would *expect* it to happen), but it's definitely annoying, there's no reason to repair things in the editor, and it's easy to fix, so I fixed it.

**Comment by JasonP01** [comment] 2024-09-05 08:41
> It's not really a bug (I would _expect_ it to happen), but it's definitely annoying, there's no reason to repair things in the editor, and it's easy to fix, so I fixed it.

Bugs are also unintended behaviour so i report things that i believe are unintended :/ 
This was clearly unintended and therefore i reported it as a bug
