### ISSUE TITLE
Gamecrash by using water-extractor in specific space

### ISSUE THREAD

**Issue by ALoTron** [Anuken/Mindustry#224] opened 2018-09-20 22:27 UTC
Hi,

I'm experiencing a gamecrash if i power up a water-extractor in a specific place (savegame attached).

Steps to reproduce the bug:
1. Place water-extractor in the region of the extractor in the top-left at the given savegame.
2. Power the extractor with an energy-source, for example with a solar panel.

Expected behavior:
The water-extractor should use some power to provide water.

Actual behavior:
After finishing the solar panel the game crashes (crash to desktop).

I couldn't reproduce the bug in sandbox-mode so far, only in freebuild-mode. I used the easy difficulty setting.

I attached a savegame, which contains a water-extractor at the top left corner (at the lava-lake). If you power this extractor, my game crashes.

Used version of the game: 4.0 Build 56
Os: Windows 10
Savegame: [Bugreport.zip](https://github.com/Anuken/Mindustry/files/2403278/Bugreport.zip)

**Comment by Anuken** [comment] 2018-09-20 22:32
This crash is caused by placing liquid junctions near edges of multi-blocks (2x2+), and has already been fixed in the development build. Until it's released, you'll have to take care to not place liquid junctions adjacent to such blocks.

**Closed by Anuken** 2018-09-20 22:32 UTC
