### ISSUE TITLE
Periodical disconnect on servers with a lot of units

### ISSUE THREAD

**Issue by Ilya246** [Anuken/Mindustry#5784] opened 2021-08-16 13:41 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*
Windows

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
129.2

**Issue**: *Explain your issue in detail.*
When there's a lot of units on servers, i periodically get disconnected with any of those errors:
![изображение](https://user-images.githubusercontent.com/57039557/129569479-3a1e09f3-477c-4dbd-af7d-fe4aa46c7e3d.png)
![изображение](https://user-images.githubusercontent.com/57039557/129569622-08e811d6-1cdf-44f7-bfe4-c37df76aa0d5.png)
I actually reported this before in https://github.com/Anuken/Mindustry/issues/5679 (happens on crawler arena) but reported it again since i noticed it happening on vanilla servers

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Be on .pl attack with ~700 units alive - did not happen when i hosted and joined a dedicated server no matter how much units were spawned
Usually *needs* at least around 500 units to happen

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[disconsave.zip](https://github.com/Anuken/Mindustry/files/6992600/disconsave.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2021-08-16 17:14
Yeah I still can't reproduce this. Here's what I attempted this time:

- Moved all my tests to a remote server with ~50ms ping - not local
- Connected with 2 clients simultaneously
- Hosted a fresh Maze sandbox game. Spawned 2k flares. Waited with both clients open for 20 minutes. No disconnects.
- Loaded your save. Server had a lot of action occurring, and routinely reached 1k+ units. No disconnects on either client in the span of 12+ minutes, or until game-over.

Some questions:

1. Was this truly a vanilla server? Did it have **zero** plugins?
2. Can anyone confirm this occurring on another server network?

**Comment by Ilya246** [comment] 2021-08-16 18:10
1. No, .pl actually isn't truly vanilla - it has jseval, NextMapPlugin, plstats and routerSnake, though i believe i had those errors occur since long ago as well with different combinations of plugins on the server (of which only jseval was consistent)
2. We can try to show those errors to people in #mindustry and see if anyone recognises them (or i can just try to wait around on .io or some other server until there's a lot of units)

**Comment by Kieaer** [comment] 2021-08-17 10:50
This error was frequently encountered when I operated the plugin multi-threaded.

**Comment by Anuken** [comment] 2021-08-17 12:30
That's why I'm trying to figure out if it's an issue on .pl specifically. If it were a fundamental threading issue on my end, presumably it would happen on *all* servers now and then. I don't know if that's the case.

**Comment by Anuken** [comment] 2021-08-18 13:01
I've looked over the relevant packet code several times, and I can't find anything wrong with it. There is no meaningful progress I can make with this issue, so I'll close it until more information is available.

Let me know if:

- you manage to reproduce it on a vanilla server (no plugins)
- someone reports it happening on a different server network
- you figure out what may be causing it, aside from high amounts of units

**Closed by Anuken** 2021-08-18 13:01 UTC
Labels: bug

**Comment by LeoSko** [comment] 2021-08-19 06:16
Side note: I do semi-automated testing on ranked server with intentionally extreme production rates which lead to 1000s of units in order to check possible scenarios and never faced such issues, which should prove the point that something is wrong with plugins and not vanilla networking.
