### ISSUE TITLE
Audio glitch in editor

### ISSUE THREAD

**Issue by 3Circle** [Anuken/Mindustry#3762] opened 2020-12-04 03:57 UTC
Platform: Windows 10

Build: Release Build 120.3 (This has been happening since beta across 2 very different PC)

Issue: When quitting out of "edit in-game" in the editor, all audio breaks (Music, sounds, everything)

Steps to reproduce: Simply just exit "edit in-game" in the editor and all audio breaks.

No mods

It has happened with every single map I quit "edit in-game"

None

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Malmik** [comment] 2020-12-04 07:29
Build: Mindustry-BE-Desktop-20210 AND Release 120.3

I can confirm that it also happens on Linux, but it's all the time from opening the game to closing it in menu and in-game.
All audio is corrupted (think of an quite strong earrape) and is so annoying that playing with volume is impossible.
Initially I sometimes got to fixing issue by muting music and ambient volume (setting to 0 in-game) and restarting game, but it doesn't do the trick now.

Ps. Only nightly build worked with that "trick"

As I am talking about different platform than @3Circle do I need to open additional bug report?

**Comment by Anuken** [comment] 2020-12-04 15:18
[Cannot reproduce.](https://github.com/Anuken/Mindustry/blob/master/ISSUES.md#i-cannot-reproduce-your-issue)

**Closed by Anuken** 2020-12-04 15:18 UTC
Labels: bug

**Comment by Awesomespore** [comment] 2021-05-07 08:56
I get this constantly when I work with the map editor, even in the most recent version (126.2), where the audio turns extremely raspy (note that the music is NOT affected, but rather the audio in the Edit In-Game when you do things like build or shoot)
_The raspy audio is quite unpleasant_
