### ISSUE TITLE
Processors issue (v109, 20.10.2020)

### ISSUE THREAD

**Issue by SkillJune** [Anuken/Mindustry#3034] opened 2020-10-20 00:40 UTC
**Platform**: *Windows 8*

**Build**: *109*

**Problem**: *Code-blocks,* @ShootX *&* @ShootY *(In processors), working with issues*

**Steps to reproduce**: *If I try use block "Sensor"*
(**For Example**:
[X = **@shootX** in **ripple1** ]
[Y = **@shootY** in **ripple1** ])
*Variables* InfoX *&* InfoY, *increase to 8*

**Steps to repair**: *Need add this blocks*:
[X = X / 8]
[Y = Y / 8]

**Save File**: *(If you want, you can check this alone in this save) *
https://drive.google.com/file/d/16KtwWixOedj-1B8LxEj-EiBXC4BUBuA5/view?usp=sharing
*(Save Name: "Issue (ByDarkJune)" )*

*And please, sorry for my bad English :з*

{X} -  I have reviewed the closed and open issues to make sure this issue has not been reported yet

**Comment by itcannotbe** [comment] 2020-10-20 08:43
Duplicate of a resolved issue -> #3021 

[X to doubt] I have reviewed the closed and open issues to make sure this issue has not been reported yet

**Closed** 2020-10-20 13:02 UTC
Labels: bug
