### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by SsNiPeR1** [Anuken/Mindustry#6677] opened 2022-03-30 16:29 UTC
**Platform**: *Linux*

**Issue**: *Cannot build because of apache dependencies.*

**Steps to reproduce**: *Just git clone <repo>, ./gradlew desktop:run*

**(Gradle) logs**: *> Configure project :
Compiling with build: 'custom build'

> Configure project :android
No keystore property found. Releases will be unsigned.
Checking the license for package Android SDK Tools in /home/ssniper1/Android/Sdk/licenses
License for package Android SDK Tools accepted.
Preparing "Install Android SDK Tools (revision: 26.1.1)".

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':android'.
> Failed to notify project evaluation listener.
   > 'void org.apache.commons.compress.archivers.zip.ZipFile.<init>(java.nio.channels.SeekableByteChannel)'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
*

---

**Comment by Anuken** [comment] 2022-03-30 16:38
Duplicate of #5721 and others.

**Closed by Anuken** 2022-03-30 16:38 UTC
Labels: bug
