### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by asdep1** [Anuken/Mindustry#2893] opened 2020-10-10 10:55 UTC
Mindustry has crashed. How unforunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: alpha build 107
OS: Windows 10 x64
Java Version: 1.8.0_72
Java Architecture: 64
0 Mods

java.lang.IllegalStateException: Frame buffer couldn't be constructed: incomplete attachment
	at arc.graphics.gl.GLFrameBuffer.build(GLFrameBuffer.java:284)
	at arc.graphics.gl.FrameBuffer.resize(FrameBuffer.java:115)
	at arc.fx.util.PingPongBuffer.resize(PingPongBuffer.java:82)
	at arc.fx.FxProcessor.resize(FxProcessor.java:72)
	at mindustry.core.Renderer.resize(Renderer.java:125)
	at arc.ApplicationCore.resize(ApplicationCore.java:29)
	at mindustry.ClientLauncher.resize(ClientLauncher.java:125)
	at arc.backend.sdl.SdlApplication.lambda$loop$12(SdlApplication.java:136)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:170)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:136)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

**Comment by Quezler** [comment] 2020-10-10 11:13
what were you doing when the error appeared? can you reproduce it and make it crash again? if so: does the `be` crash to?

**Comment by DeltaNedas** [comment] 2020-10-10 11:24
pretty sure it means OOM but for vram, i got that when trying to preview a 32k long schematic

**Comment by asdep1** [comment] 2020-10-10 13:02
i have crash on i change my graphics settings fullscreen : on

**Comment by Anuken** [comment] 2020-10-10 15:08
Can't reproduce, won't fix.

**Closed by Anuken** 2020-10-10 15:08 UTC
Labels: bug
