### ISSUE TITLE
Ores "corrupt" randomly

### ISSUE THREAD

**Issue by ThePythonGuy3** [Anuken/Mindustry#2463] opened 2020-08-29 19:43 UTC
**Platform**: *Windows*

**Build**: *Just updated v6 from github and compiled it. Not a BE*

**Issue**: *OreBlocks (In this case just copper) started getting "corrupted" each time i open/close the game for some reason. instead of the normal sprites an "ohno" appears where no ohnos appeared before.*

**Steps to reproduce**: *Go into a map with an ore (copper in this case) and close and reopen the game. just load the map*
(1)
![image](https://raw.githubusercontent.com/ThePythonGuy3/Mindustryv6Resprite/master/unknown%20(2).png)
(2)
![image](https://raw.githubusercontent.com/ThePythonGuy3/Mindustryv6Resprite/master/unknown.png)
this was before normal copper. then i reopened the map (1), and did it again (2).

**Link to mod(s) used, if applicable**: *none*

**Crash report, if applicable**: *none*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by RandomTNT** [comment] 2020-08-29 21:15
Well, i gonna check the code

**Comment by RandomTNT** [comment] 2020-08-29 21:15
Btw, link to the bulid u using

**Comment by ThePythonGuy3** [comment] 2020-08-30 09:26
it isnt a build, i just updated using git, and then compiled it

**Comment by ThePythonGuy3** [comment] 2020-08-30 11:52
what

**Comment by Anuken** [comment] 2020-08-30 13:16
This doesn't happen to me, and it would be very obvious if it happened to someone else. Either you have some changes causing it locally or very specific circumstances that I can't reproduce. This won't be fixed.

**Closed by Anuken** 2020-08-30 13:16 UTC
Labels: bug
