### ISSUE TITLE
Derelict Battlefield 3: Electric Boogalee

### ISSUE THREAD

**Issue by BlueWolf3682** [Anuken/Mindustry#6492] opened 2022-01-13 21:16 UTC
**Special Note**: *This issue has already been reported multiple times. However, it remains unresolved. **Please do not close this bug report until this is patched, as I am continually asked questions about JSON sectors.***

**Platform**: *Android/Windows*

**Build**: *release build 135, BE 22285*

**Issue**: *Remember that good old issues of maps/derelict-battlefield.msav? well, it has now plagued 5 other users.*

**Steps to reproduce**: *Same as before - I do not expect you (Anuke) specifically to reproduce it, but for anyone testing:*
1. Go to the "Mods" section in the main menu.
2. Download Exotic Mod and restart the game.
3. find the sector with the label "derelict-battlefield" and attempt to launch to the sector. 

*Either it will function correctly, as is Anuke's case, or it will be a blank gray sector unable to be launched to, or you will get a parse error on reloading the game.*

**Link(s) to mod(s) used**: https://github.com/BlueWolf3682/Exotic-Mod

**Save file**: *This is not save specific - it appears more or less client specific. Even with a save file, your results will differ.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *My clients do not have the parse error version of the issue.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2022-01-13 21:49
Have any of these people posted their logs? I still don't know what the parse error is. I'm not sure what the utility in keeping this issue here is when there's not enough information for anyone to solve it.

**Comment by BlueWolf3682** [comment] 2022-01-13 22:38
Leaving this open assures that future issues of this type are not created. If others experienced this bug, they will see that it is known and unresolved.

The parse error is simply: "File not found: maps/derelict-battlefield.msav". I will attempt to find someone who has this parse error and knows how to get the last log from their device.

**Comment by BlueWolf3682** [comment] 2022-01-15 10:37
[E] Error for derelict-battlefield / C:/Users/Castillo/AppData/Roaming/Mindustry/mods/BlueWolf3682-Exotic-Mod-b0568ad.zip/BlueWolf3682-Exotic-Mod-b0568ad/content/sectors/derelict-battlefield.hjson:
arc.util.ArcRuntimeException: File not found: maps\derelict-battlefield.msav (internal)
	at arc.files.Fi.read(Fi.java:199)
	at arc.files.Fi.read(Fi.java:216)
	at mindustry.io.MapIO.createMap(MapIO.java:39)
	at mindustry.maps.Maps.loadInternalMap(Maps.java:107)
	at mindustry.maps.generators.FileMapGenerator.<init>(FileMapGenerator.java:20)
	at mindustry.type.SectorPreset.<init>(SectorPreset.java:25)
	at mindustry.mod.ContentParser.lambda$new$6(ContentParser.java:384)
	at mindustry.mod.ContentParser.parse(ContentParser.java:535)
	at mindustry.mod.Mods.loadContent(Mods.java:635)
	at mindustry.core.ContentLoader.createModContent(ContentLoader.java:74)
	at mindustry.ClientLauncher.lambda$setup$5(ClientLauncher.java:102)
	at arc.assets.AssetManager$1.loadSync(AssetManager.java:334)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:109)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:148)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:166)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:154)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:45)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:74)

I cut it from the full log, the users has a lot more mod errors than just this one.

**Comment by Anuken** [comment] 2022-01-15 16:24
> the users has a lot more mod errors than just this one.

Errors, or warnings? Have they tried disabling their other mods?

**Comment by BlueWolf3682** [comment] 2022-01-15 22:22
Some errors, non critical ones like BetaMindy having an unloaded sound (sks fault). 
However, I have confirmed this issue happens **without any other mods being installed or enabled.**

**Comment by Anuken** [comment] 2022-01-22 23:27
I'm closing this, as:

- The most obvious problem reported here is already fixed, and that may affect the other bug (although this is unlikely).
- I cannot reproduce it anywhere, and neither can most other people.
- I have no idea what causes it.
- I can make **no** progress in fixing this, and there is nothing left to discuss here. Anyone reporting the issue is **required** to search it in the closed issues - people who don't read the directions are going to create duplicates anyway.

**Closed by Anuken** 2022-01-22 23:27 UTC
Labels: bug
