### ISSUE TITLE
Sei pathfinding bug

### ISSUE THREAD

**Issue by Ineedause** [Anuken/Mindustry#5249] opened 2021-05-16 01:20 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*
Mac
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
126.2
**Issue**: *Explain your issue in detail.*
Sei gets stuck on natural terrain, such as ground blocks when trying to path find to a rally command center because it counts ground blocks as a valid path
**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
make a U shape in the sandbox and place seis in the bottom of the u, now make another u and they connect via the tops of the u's. make sure there is a non liquid block in between the two u's. and on the bottom of the other U. when the command center is set to rally the seis will sometimes bunch up at the bottom of the first u. This usually happens in multiplayer games with sand blocks. Although I have seen it happen else where before. I don't have a exact map of the first time I saw this bug because it got removed from the server I use. But the zip file below contains a "replica" of the thing I am trying to explain. The bug also is random, it only happens sometimes.

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*
no mods
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

[bug.msav.zip](https://github.com/Anuken/Mindustry/files/6488513/bug.msav.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2021-05-16 01:47
Can't reproduce, won't fix.

**Closed by Anuken** 2021-05-16 01:47 UTC
Labels: bug
