### ISSUE TITLE
Overflow/Underflow gate exit bug

### ISSUE THREAD

**Issue by serdarakkilic** [Anuken/Mindustry#1449] opened 2020-01-26 14:26 UTC
**Platform**: *Mac OS 10.13.6*
**Build**: *103.4 - Steam*
**Issue**: *Overflow and Underflow Gates are routing unnecessary items when they are connected to a conveyor belt like there is an overflow happening on the conveyor belt*
**Steps to reproduce**: *Just put an overflow gate into a section of a saturated conveyor belt, have an exit point for overflown items and observe:*
![01](https://user-images.githubusercontent.com/12392315/73136534-b884c080-405f-11ea-9578-e413cba070cc.gif)

It doesn't even need to be a fully saturated belt for this to happen:
![02](https://user-images.githubusercontent.com/12392315/73136564-0ef1ff00-4060-11ea-9d43-4c3c6207a19d.gif)

Having a transportation component faster than a titanium conveyor which has it's own item storage may fix this issue. Like bridges, junctions:
![03](https://user-images.githubusercontent.com/12392315/73136599-58dae500-4060-11ea-99ef-dceb68e48756.gif)

Underflow gates also has the same issue:
![04](https://user-images.githubusercontent.com/12392315/73136639-c0913000-4060-11ea-9f4f-f81c367e7e6c.gif)

@Anuken You have closed this issue, but it is not fixed in new builds. I wasn't able to open it again. I needed create a new issue about this. Sorry for that :(

**Comment by Anuken** [comment] 2020-01-26 15:41
This doesn't happen to me. Your second GIF with a non-saturated conveyor was reproduced and fixed; I tested at different FPS values and no erroneous overflow occurred. The only thing that may still occur is precision errors due to fluctuating FPS and different speeds after input/output. This won't be fixed.

**Closed by Anuken** 2020-01-26 15:41 UTC
