### ISSUE TITLE
Saving a game doesnt work

### ISSUE THREAD

**Issue by dhaveman** [Anuken/Mindustry#418] opened 2019-03-02 23:31 UTC
If I close the app and come back or try to load from a save. I see what looks like a super zoomed out view of the game with a few scattered colored pixels.  I have a Galaxy S9

**Comment by Anuken** [comment] 2019-05-07 23:26
Similar issues have happened with other people using build 40, but I have yet to see anyone report something like this for the latest builds. As I have no idea if it still happens, and I can't reproduce it, I'll close this issue until further notice.

**Closed by Anuken** 2019-05-07 23:26 UTC
