### ISSUE TITLE
Mod translation has problem on the official Android release by DEFAULT

### ISSUE THREAD

**Issue by abomb4** [Anuken/Mindustry#3876] opened 2020-12-09 04:19 UTC
**Platform**: *Android*

**Build**: *release build 121*

**Issue**: 
By default (Clean installation of game), information of mod contents is displayed in English instead of the system language (I'm sure translation files in `mod/bundle` exist and are valid)
When I switch the game display language to another language and then switch back, the mod content will be displayed correctly.
This problem not produced on Windows, Android beta version or Android custom builds.

**Steps to reproduce**:
1. Prepare an Android system and set its language to non-English
2. Prepare a mod that contains valid translation files in `bundle/` (contains English and Android system language in the step 2)
3. Install Mindustry from itch.io or Google Play
4. Start game, install the mod from step 2
5. (problem) Check the information of the Mod content in game, it will be displayed in English instead of the system language. It should be displayed in system language.
6. Set the game display language to another one and then switch back, the mod content will be displayed in the correct language

**Link(s) to mod(s) used**: 
- https://github.com/abomb4/dimension-shard
- https://github.com/abomb4/super-cheat

**Save file**: *No save file need*

**(Crash) logs**: *Not a crash*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-12-09 04:32
> This problem not produced on Windows, Android beta version or Android custom builds.

If it can't be reproduced in custom builds, then I can't test it, because *all* my builds are custom. It's also worth noting that the beta has exactly the same language loading code, as far as mods are concerned.

My guesses:

- You have a specific Android system locale that is not exactly equivalent to `zh_CN`, so by default mods don't use it unless you manually reset your language to be `zh_CN` in the menu.
- Something changed on your device or environment that caused locale problems. I certainly haven't changed anything in that department recently.

Won't fix.

**Closed by Anuken** 2020-12-09 04:32 UTC
Labels: bug
