### ISSUE TITLE
Broken Bridge Conveyors

### ISSUE THREAD

**Issue by SownGryphon** [Anuken/Mindustry#2534] opened 2020-09-10 22:15 UTC
**Platform**: *Windows*

**Build**: *Bleeding Edge Build 9635*

**Issue**: *When I loaded into my game, several bridge conveyors had visual bugs. Relaunching hte game seems to have fixed it.*

**Steps to reproduce**: *Just loaded into my game*

**Link(s) to mod(s) used**: *None*

**Save file**: *
![Screenshot (84)](https://user-images.githubusercontent.com/71104090/92814725-e0664000-f406-11ea-9718-6f0419cd3417.png)
*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by SownGryphon** [comment] 2020-09-10 22:19
Update: after relaunching the game, all of the natural walls in the sector seem to have disappeared.
![Screenshot (85)](https://user-images.githubusercontent.com/71104090/92815296-70a48500-f407-11ea-97ff-b2a9fab6b49b.png)

**Comment by Anuken** [comment] 2020-09-10 23:05
Duplicate of #2419

**Closed by Anuken** 2020-09-10 23:05 UTC
Labels: bug
