### ISSUE TITLE
Bridge Conveyor Graphical Glitch

### ISSUE THREAD

**Issue by iLagSoUhax** [Anuken/Mindustry#2419] opened 2020-08-25 13:53 UTC
**Platform**: Windows

**Build**: 9461

**Issue**: graphical glitch which makes bridge conveyors have a stroke and be placed in a diagonal way

**Steps to reproduce**: Place a Bridge Conveyor

**Link to mod(s) used, if applicable**: N/A

**Crash report, if applicable**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

![image](https://user-images.githubusercontent.com/65382389/91182702-23869a80-e708-11ea-9512-49223844e38b.png)

**Comment by Anuken** [comment] 2020-08-25 14:08
![image](https://user-images.githubusercontent.com/10100000/91184359-8b15f900-e6ba-11ea-9dae-57da975b8e3a.png)

Doesn't happen to me.

**Comment by iLagSoUhax** [comment] 2020-08-25 14:24
Huh, it does for me, Can you try the same with the Fortress Map @Anuken

**Comment by Quezler** [comment] 2020-08-25 15:00
@iLagSoUhax could you maybe provide the save file containing the bridges from your screenshot?

**Comment by iLagSoUhax** [comment] 2020-08-25 15:09
ah, now where are those?

**Comment by Quezler** [comment] 2020-08-25 15:11
the rightmost button will allow you to export your save:

![Screen Shot 2020-08-25 at 17 11 27](https://user-images.githubusercontent.com/3179271/91192273-0779fd80-e6f6-11ea-907c-9f0b25c3a3ba.png)

**Comment by iLagSoUhax** [comment] 2020-08-25 15:12
Alright, do you mind if i do it tomorrow? It's getting late.

**Comment by Quezler** [comment] 2020-08-25 15:13
take your time 🙂

**Comment by iLagSoUhax** [comment] 2020-08-25 15:15
:D

**Comment by Anuken** [comment] 2020-08-25 15:16
> Can you try the same with the Fortress Map

Doesn't happen there either.

**Comment by Anuken** [comment] 2020-08-27 14:17
Closing:
- This doesn't happen to me in any scenario on any device
- This is a very obvious bug that doesn't seem to happen to anyone else
- If I can't reproduce it, I can't fix it

**Closed by Anuken** 2020-08-27 14:17 UTC
Labels: bug
