### ISSUE TITLE
Items not going through Junctions

### ISSUE THREAD

**Issue by Luxray5474** [Anuken/Mindustry#61] opened 2018-01-05 13:23 UTC
![bug7](https://user-images.githubusercontent.com/30189017/34610978-8f401224-f1f1-11e7-98cd-ec4f9cfd51b1.gif)

This started happening when i came back from rebuilding my defenses. 

EDIT: it seems all but one of my junctions aren't working as they should.
![bug8](https://user-images.githubusercontent.com/30189017/34611237-b2ceb7b2-f1f2-11e7-80e4-52c714138fad.gif)

I was able to get them to work normally again after re-loading the save.

**Comment by Anuken** [comment] 2018-01-05 15:50
I'm aware that this bug exists, but I've never been able to reproduce it myself. I think it's caused by tile entities somehow overlapping a single tile or not being placed properly.

**Comment by Anuken** [comment] 2018-02-09 21:09
Seems to have been fixed by the latest betas and re-coding of junctions. Closing unless it is found again.

**Comment by Anuken** [comment] 2018-03-03 16:45
Still seems to occur rarely on multiplayer, with individual junctions/tunnels instead of whole swaths like before. Haven't been able to reproduce it myself at all.

**Comment by AlexThePrettyGood** [comment] 2018-03-14 02:50
Using omnidrills on stone is a waste, as omnidrills mine at the same speed as stone drills

**Comment by Anuken** [comment] 2018-05-30 19:01
Alright, I think this bug has *finally* been squashed now. I haven't seen any reports for weeks, now that the last clogging issue got resolved.

**Closed by Anuken** 2018-05-30 19:01 UTC
Labels: bug, to do
