### ISSUE TITLE
A locally imported mod missing after restarting application

### ISSUE THREAD

**Issue by kerong08ng** [Anuken/Mindustry#1251] opened 2019-12-23 04:14 UTC
**Platform**: *Android*

**Build**: *101.1*

**Issue**: *Mod Missing after restarting the application*
I have imported this mod via downloading the zip file and taking the folder that contains mod.json to perform locally import on Android version Mindustry.

This mod I imported, https://github.com/aaRecessive/allmechs

After restarting the application, this mod is missing in the mod list while I have tried to add it back from local again, error popup saying there are existing mod with same name.

**Steps to reproduce**: *1.start Mindustry apps*
2.go to mod menu page
3.press import mod
4.choose the allmech.zip
5.enable the mod and reload the game.
6.the mod is on modlist right now.
7.Terminate the application and restart it
8.go to mod menu page and the mod is missing
9.start a custom game, the mod content are not shown too.

**Comment by Anuken** [comment] 2019-12-23 04:16
Duplicate of #1055

**Closed by Anuken** 2019-12-23 04:16 UTC
