### ISSUE TITLE
Junction placing items weirdly

### ISSUE THREAD

**Issue by ICrowleyI** [Anuken/Mindustry#72] opened 2018-01-12 21:54 UTC
The coal miner below the junction seems to output coal through the junction on the conveyor in front of the junction.
![junction placing item wierd](https://user-images.githubusercontent.com/30113543/34896782-6e839542-f7eb-11e7-8922-8b2eaf3810b2.gif)

**Comment by Anuken** [comment] 2018-01-15 20:14
Should be fixed in the latest beta; I can't reproduce it anymore.

**Closed by Anuken** 2018-01-15 20:14 UTC
