### ISSUE TITLE
A map can be put into a state from which it can never revert

### ISSUE THREAD

**Issue by BlueManedHawk** [Anuken/Mindustry#6378] opened 2021-11-26 06:15 UTC
**Platform**: *Linux*

**Build**: *135*

**Issue**: *There exist several blocks which can be destroyed, but not built, meaning that a map can be put into a state from which it can never recover.  This seems to just be the boulders and spore cluster.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *Not applicable.*

**Save file**: *Mandating people to provide a save file is a horrible invasion of privacy.*

**(Crash) logs**: *Not applicable.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MissAmity** [comment] 2021-11-26 08:59
h

**Comment by MissAmity** [comment] 2021-11-26 09:04
> Mandating people to provide a save file is a horrible invasion of privacy
how horrible that is
i can't see this as a bad thing at all

**Comment by Phinner** [comment] 2021-11-26 11:39
> There exist several blocks which can be destroyed, but not built, meaning that a map can be put into a state from which it can never recover. This seems to just be the boulders and spore cluster.

Yes, because they are props, not intended for building... They can be either generated or added directly in the editor.

> Mandating people to provide a save file is a horrible invasion of privacy.

You are joking right ? Why are you concerned for your privacy with a open source game ? Plus saves are litteraly regular maps files with a game state. You can see by yourself the [code](https://github.com/Anuken/Mindustry/blob/master/core/src/mindustry/io/SaveIO.java).

**Comment by BlueWolf3682** [comment] 2021-11-26 13:06
Well I mean, you can not provide the save and have Anuke close the issue without fixing it because he cannot reproduce it, or you can provide it and have a higher chance of having it fixed.

**Comment by Anuken** [comment] 2021-11-26 15:51
I started typing out a genuine response to this "report", but something about this style seemed very familiar, so I searched up the author's other issues. My conclusion is that they're either intentionally trolling, or just like posting incredibly unhelpful bug reports. Possibly a mix of both.

Some examples:
- [Actually trying to argue that the sun not having scientifically accurate proportions is a bug](https://github.com/Anuken/Mindustry/issues/4153)
- [Another issue with no save due to "privacy concerns"](https://github.com/Anuken/Mindustry/issues/4903) - "I can't think of anything in particular, but I'm certain it will be there" (?????)
- [Absolutely bizarre problems (1)](https://github.com/Anuken/Mindustry/issues/5528) [with basic unzipping that nobody else has experienced (2)](https://github.com/Anuken/Mindustry/issues/5524)

**Closed by Anuken** 2021-11-26 15:51 UTC
Labels: bug

**Comment by Bottinator22** [comment] 2021-11-26 19:20
Ah yes "save file privacy concerns" the only reason a save file would be a privacy concern is if you put actually private information, such as your name or face, onto the save

which is kinda stupid, and you can just remove that stuff

**Comment by Bottinator22** [comment] 2021-11-26 19:22
This would make sense if you were talking about maps with banned blocks that provide those banned blocks already placed, since when you start deconstructing those you can't reconstruct them, but props?
