### ISSUE TITLE
闪退,显示空指针错误-红米10A-miui12-最新版本145

### ISSUE THREAD

**Issue by AWSZ12112** [Anuken/Mindustry#8719] opened 2023-06-18 09:03 UTC
![Screenshot_2023-06-18-12-40-34-569_com miui thirdappassistant](https://github.com/Anuken/Mindustry/assets/136962657/a6d75bc8-4c00-4b3f-809b-7d7e3af6b1af)
![Screenshot_2023-06-18-12-41-18-064_com miui thirdappassistant](https://github.com/Anuken/Mindustry/assets/136962657/a8eb1aa9-9d44-4206-b608-6f9028679799)
![Uploading Screenshot_2023-06-18-12-41-22-669_com.miui.thirdappassistant.jpg…]()

**Comment by BalaM314** [comment] 2023-06-18 12:35
Duplicate of #8718

**Closed** 2023-06-18 13:01 UTC
