### ISSUE TITLE
Export data is not working

### ISSUE THREAD

**Issue by antoniogamiz** [Anuken/Mindustry#2215] opened 2020-07-08 19:22 UTC
**Platform**: *Linux*

**Build**: *104.6*

**Issue**: *I am trying to export my data from my phone to my windows pc.*

**Steps to reproduce**: 

From my android phone:

1. Open the game.
2. Settings.
3. Game data.
4. Export data. (
5. Send me that zip to my windows pc.

From my windows pc:
1. Open the game.
2. Settings.
3. Game data.
4. Import data.
5. Error.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-07-08 19:37
Works fine on my computer/phone, as well as on many other people's setups. Either you're importing the wrong file, the file is being corrupted during sending, or you've encountered a platform-specific bug that I can't reproduce. 

This won't be fixed.

> Platform: Linux

What does Linux have to do with this issue if you say you are are exporting Android data to Windows?

**Closed by Anuken** 2020-07-08 19:37 UTC
Labels: bug

**Comment by DeltaNedas** [comment] 2020-07-08 21:24
android uses the linux kernel silly anuke im sure you think he meant GNU/Linux haha

**Comment by Anuken** [comment] 2020-07-08 22:15
*yes I know that Android uses the Linux kernel but no sane person on Android claims that they're "using linux as a platform" unless they want to be intentionally misleading, because your typical desktop Linux setup is going to be completely different from Android*
