### ISSUE TITLE
6.0 Alpha - Area that Cannot be Built On

### ISSUE THREAD

**Issue by Draco18s** [Anuken/Mindustry#2623] opened 2020-09-20 00:50 UTC
**Platform**: Windows

**Build**: 105

**Issue**: Dark area for me (host) but not for client (coop friend) where buildings could not be placed.

**Steps to reproduce**: Unsure at this time. May be map-specific. Not multiplayer specific other than connected clients do not see the fog. Clients can attempt to place buildings in the area, but they won't be built, host cannot even place ghosts.

This is what I could see my end:
![20200919192252_1](https://user-images.githubusercontent.com/1750680/93691843-c08ee600-fab0-11ea-8ec3-5ed7833d3d25.jpg)

This is what my friend could see:
![image](https://user-images.githubusercontent.com/1750680/93691849-d3a1b600-fab0-11ea-9c9b-afcbbf3558c5.png)

- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
(The word "build" appears in everything, so this one is a bit hard to search for)

**Comment by Anuken** [comment] 2020-09-20 00:54
Duplicate of #2573 (all sectors have extra fog at borders, which clients don't see)

**Closed by Anuken** 2020-09-20 00:54 UTC
Labels: bug

**Comment by Draco18s** [comment] 2020-09-20 02:21
Huh! I had seen that report and thought it was something entirely different.

**Comment by djradnad** [comment] 2020-09-21 20:31
> Huh! I had seen that report and thought it was something entirely different.

yea easy to miss I only mentioned this bit at the end.
