### ISSUE TITLE
Schematic Search bar Keyboard Bug

### ISSUE THREAD

**Issue by Odin580** [Anuken/Mindustry#5744] opened 2021-08-11 19:40 UTC
**Platform**: Android

**Build**: BE 21651

**Issue**: When using the search bar on the schematics page, the keyboard stays up if you leave the page (also can click through the keyboard via grey space below space bar).

**Steps to reproduce**: 

https://user-images.githubusercontent.com/88634312/129089137-fc6f4f49-63e7-4b83-924d-c923fa90929d.mp4

Vid below shows keyboard stuck on screen after getting out of schematic page.  Later found out if I pull down my Android notifications, back button shows up at bottom and I can click that to remove the keyboard.

https://user-images.githubusercontent.com/88634312/129089177-e5c7fa47-d42d-459e-a7c6-e45bda83eb70.mp4

Video below is how the typing bar works elsewhere.  Note the lack of grey below the space bar, likewise allows me to off click, where it collapses the keyboard.

https://user-images.githubusercontent.com/88634312/129090622-dc22b098-fa86-4af5-9ba8-f1b8ead47470.mp4

Video below is me clicking through the grey space below space bar where I click the "import schematics" button through keyboard.  Also, I realized later the first clip I was clicking through this grey bar as well and hitting the button on left, think it says "back".  It just exits the schematics page.  Either way, I'm unable to get the keyboard to disappear via in-game means, and the search bar doesn't behave like other input windows in-game. 

https://user-images.githubusercontent.com/88634312/129090753-98a9d039-753b-400a-8f66-d7251ef7550b.mp4

**Link(s) to mod(s) used**: None, vanilla version used.

**Save file**: 
[MindustrySearchTest.zip](https://github.com/Anuken/Mindustry/files/6970848/MindustrySearchTest.zip)

**(Crash) logs**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2021-08-11 19:45
Cannot reproduce. On my phone, it is not possible to tap through the keyboard onto the back/import buttons on the dialog, and hence it is impossible to even exit the schematics dialog without closing the keyboard first.

**Closed by Anuken** 2021-08-11 19:45 UTC
Labels: bug

**Comment by Odin580** [comment] 2021-08-11 20:01
I did some further testing with Microsoft Keyboard. 

https://user-images.githubusercontent.com/88634312/129094816-5a6d1e88-6719-4778-a020-f146caf0b6ce.mp4

Same exact thing, the back button doesn't show up with keyboard unless I access my android menu.

However, on the other typing planes the back button pops up, and everything works as it should. 


https://user-images.githubusercontent.com/88634312/129095047-eaf059fe-cd6e-44ef-89b2-c64f53a49b4c.mp4

**Comment by joshuaptfan** [comment] 2021-08-11 20:05
What Android version and what keyboard does the bug occur with?

**Comment by Anuken** [comment] 2021-08-11 20:13
Even if it does not disappear automatically, can you not swipe up and close the keyboard..?

**Comment by BlueWolf3682** [comment] 2021-08-11 20:17
I can confirm reproduction of multiple (very annoying) bugs with the keyboard not disappearing, including one notable bug where it re-appears if I close it with the undo button.

**Comment by Anuken** [comment] 2021-08-11 20:31
In any case, I can make the keyboard disappear when its associated text field is gone. I still don't know how it is able to pass through touch input under itself, and I'm not seeing any documentation on the topic.

**Comment by joshuaptfan** [comment] 2021-08-11 21:15
> I still don't know how it is able to pass through touch input under itself, and I'm not seeing any documentation on the topic.
The area he's tapping on that's letting taps through is a buffer area under the keyboard to shift it up. Some Android keyboards have a setting to shift the keyboard up to not cramp your thumbs. Whether taps can pass through will depend on the particular quirks of the keyboard software.

**Comment by Odin580** [comment] 2021-08-11 22:09
@joshuaptfan I'm on Android 9, I've shown it happening with Google Keyboard and Microsoft Swift Keyboard.  I can test with more keyboards from the play store if you like.

@Anuken Yes, swiping up shows the back button, same thing as swiping down.  In the other input fields the back button is present by default, and I can off click and it completely exits the input window and keyboard goes away (such as when creating a new schematic, when re-naming a schematic, and when adding a description to a schematic).  The behavior uniquely shows up with the search bar input, so there seems to be something different about it to me.

@joshuaptfan I haven't changed any settings on my keyboard as well as have tested on two keyboards (I'll check keyboard settings though to see if I can change behavior), I'm also wondering why it only does it with the search input box and not the other input boxes, any insights?

The unique thing is that the buffer area on the other input planes shows all my bottom buttons where that space is provided.
