### ISSUE TITLE
Controll issue

### ISSUE THREAD

**Issue by Slawmee** [Anuken/Mindustry#5138] opened 2021-04-22 11:22 UTC
**Platform**: *Android*

**Build**: *126..2*

**Issue**: *When Im controlling the Sei or Omura,it will start moving by itself like pathfinding even im doing nothing but i can shoot.*

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MrDuck557** [comment] 2021-04-22 12:47
Duplicate of #5137, close now

**Closed** 2021-04-22 12:57 UTC
Labels: bug
