### ISSUE TITLE
After Wiping my Game Files, Booting into Ground Zero Crashed the Game

### ISSUE THREAD

**Issue by Auseawesome** [Anuken/Mindustry#3025] opened 2020-10-19 08:43 UTC
Version: bleeding-edge build 10613
OS: Windows 10 x64
Java Version: 1.8.0_261
Java Architecture: 64
0 Mods

java.lang.NullPointerException
	at mindustry.ui.dialogs.PlanetDialog.lambda$updateSelected$22(PlanetDialog.java:460)
	at arc.scene.Element$9.changed(Element.java:967)
	at arc.scene.event.ChangeListener.handle(ChangeListener.java:13)
	at arc.scene.Element.notify(Element.java:165)
	at arc.scene.Element.fire(Element.java:136)
	at arc.scene.ui.Button.setChecked(Button.java:106)
	at arc.scene.ui.Button$1.clicked(Button.java:92)
	at arc.scene.event.ClickListener.touchUp(ClickListener.java:77)
	at arc.scene.event.InputListener.handle(InputListener.java:34)
	at arc.scene.Scene.touchUp(Scene.java:342)
	at arc.input.InputMultiplexer.touchUp(InputMultiplexer.java:137)
	at arc.input.InputEventQueue.drain(InputEventQueue.java:71)
	at arc.backend.sdl.SdlInput.update(SdlInput.java:104)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:152)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:52)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)

Game Crashed at launch of ground zero, campaign unplayable

**Steps to reproduce**: After the campaign was chnaged I erased my data to start a fresh new campaign when I booted up ground zero it crashed the game

[Mindustry.zip](https://github.com/Anuken/Mindustry/files/5400357/Mindustry.zip)

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by itcannotbe** [comment] 2020-10-19 08:52
Duplicate of #3017 
Also......

    [X to doubt] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Auseawesome** [comment] 2020-10-19 08:53
> Duplicate of #3017
> Also......
> 
> [X to doubt] I have searched the closed and open issues to make sure that this problem has not already been reported.

Wow... sorry for duplicate. How do i take this down?

**Closed** 2020-10-19 08:54 UTC
Labels: bug
