### ISSUE TITLE
Bleeding edge crash on update

### ISSUE THREAD

**Issue by Erisfiregamer1** [Anuken/Mindustry#3663] opened 2020-11-30 13:28 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux* Windows.

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* Every BE build to date.

**Issue**: *Explain your issue in detail.*
Every time I update Bleeding Edge, I have to deal with Mindustry crashing. I have to reopen it again to make it work. The old tab eventually gets the "Mindustry is not responding" from windows, and I close it.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
Update BE on my device.
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME.*
Not a bug while playing.
If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**Crash report**: *The contents of relevant crash report files. REQUIRED if you are reporting a crash.*
It didn't output a crash report.
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment] 2020-11-30 13:40
check the crashes folder in wherever the application data is stored.

**Comment by Erisfiregamer1** [comment] 2020-11-30 13:48
I tried that. Again, no output. Im guessing Java encountered something that it couldn't log?

**Comment by Quezler** [comment] 2020-11-30 13:51
then i'm afraid its better to close this issue since anuke won't be able to reproduce or trace whatever happened 🤔

**Closed** 2020-11-30 14:44 UTC
Labels: bug

**Comment by quanium** [comment] 2020-12-04 09:44
[last_log.txt](https://github.com/Anuken/Mindustry/files/5641836/last_log.txt)
![after upgate from 20142 to 20210](https://user-images.githubusercontent.com/738857/101148185-62dd5500-362e-11eb-8ddf-ba39be5bae1c.jpg)
Same bug + log and screenshot

**Comment by Erisfiregamer1** [comment] 2020-12-09 12:49
Oh heck, someone else is getting it? Good. Ill repoen it...

**Comment by Erisfiregamer1** [comment] 2020-12-09 12:50
Or, I cant.

**Comment by quanium** [comment] 2020-12-10 12:40
Same bug from client-be-20274 to client-be-20284.jar
i made java dump 
https://mega.nz/file/Ea5mBSIQ#29jKgfG1U41mb_yGuti0tRwZb57gqEg9Ks2C5tOkHN4

![image](https://user-images.githubusercontent.com/738857/101773445-d505dc00-3afd-11eb-9af6-8b7f7ef7586a.png)

may be this can help
