### ISSUE TITLE
Sprite Overrides Don't Work Half The Time

### ISSUE THREAD

**Issue by MEEPofFaith** [Anuken/Mindustry#1879] opened 2020-04-16 18:43 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux* Windows

**Build**: *The build number under the title in the main menu. Required.* 104.10

**Issue**: *Explain your issue in detail.* Sprite overriding doesn't seem to work and remain with the default sprite half the time.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.* I tried replacing the current revenant sprite with the one I drew based off of your concept art, but despite being properly named "revenant.png" and being placed in sprites-override/units, it wouldn't show. The 2 other sprite overrides in the same mod are also not showing up.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-04-16 19:05
This works fine for me. Send me the mod.

**Comment by DeltaNedas** [comment] 2020-04-16 20:40
also womm

**Comment by Anuken** [comment] 2020-04-16 21:36
Can't reproduce on 6.0 or 5.0, even across reloads and multiple disables/enables. This won't be fixed without more information.

**Closed by Anuken** 2020-04-16 21:36 UTC

**Comment by MEEPofFaith** [comment] 2020-04-16 21:45
[Title Screen](https://gyazo.com/df1a6c50f3877eb21c98d8d60d2d2c5d)
[Folder](https://gyazo.com/f97ed01ca9a3e2694226cacd995cab91)

Mod is enabled, but sprites aren't overriding.

**Comment by MEEPofFaith** [comment] 2020-04-16 21:45
Someone mentioned something about VRam, though I don't know how to check how much VRam I have, just how to check for Ram.

**Comment by Anuken** [comment] 2020-04-16 23:29
Are you sure you have the right version of the mod loaded?

**Comment by MEEPofFaith** [comment] 2020-04-17 01:14
yes

**Comment by DeltaNedas** [comment] 2020-04-17 03:13
if you run out of vram (just ram with hd graphics) i think it would crash and burn

**Comment by MEEPofFaith** [comment] 2020-04-17 04:05
So I'm overriding sprites in MEEPofFaith/anuke-concept-art to replace things with Anuke's new concept art sprites. It was fine with just the revenant, but after adding the reaper both overrides stopped working.

**Comment by BlueWolfGaming** [comment] 2020-05-01 02:48
i dont seem to have any issues with overriding other than with mech sprites

**Comment by sk7725** [comment] 2020-10-21 11:21
@Anuken , can you take a look again into this? I also get the same results, in 10643 with sk7725/Immundustry; except it works *way* less than half the time. Also, I noticed sprites-override only mods work fine, the ones with both sprites and sprites-override refuse to work.

**Comment by Anuken** [comment] 2020-10-21 14:36
@sk7725 I've pointed this out to someone before, but the ore sprites you see in game's sprite folder are *never actually used in-game*. Your mod *is* overriding those sprites, but what you see in-game is a generated sprite with a different name that has a shadow added. The correct name for the first variant of copper is `ore-copper1`.

**Comment by sk7725** [comment] 2020-10-24 12:52
> @sk7725 I've pointed this out to someone before, but the ore sprites you see in game's sprite folder are _never actually used in-game_. Your mod _is_ overriding those sprites, but what you see in-game is a generated sprite with a different name that has a shadow added. The correct name for the first variant of copper is `ore-copper1`.

I see, but other environmental blocks did not work either(ex. sand). Also, in v5 `sk7725/Commandblocks` had a `white-tree.png` override that barely worked.
