### ISSUE TITLE
Bug_UnitRadar

### ISSUE THREAD

**Issue by Ubivashka1998** [Anuken/Mindustry#5006] opened 2021-03-27 04:47 UTC
**Platform**: *Android*

**Build**: *126.1*

**Issue**: *When one unit finds an enemy unit, then somehow information about the enemy unit is transferred to other allied units, although everything works fine with the UnitLokate and turret.*

**Steps to reproduce**: *It is necessary to delay several Nova units and let one unit go to the core / spawn. Place an enemy unit on Nova's path.*

**Link(s) to mod(s) used**: *[Video](https://drive.google.com/file/d/1I42iXJu9zJ6rFXjiQ8hHlWRQ3hfLVjim/view?usp=drivesdk), [Scheme](https://drive.google.com/file/d/1I5CFon4OUAj9AaF1qItPHU0nYCTZgY0h/view?usp=drivesdk)*

**Comment by PolloUsami** [comment] 2021-03-27 11:24
anuken will close this for two reasons

1) the template
2) he has sayed before that he will dont check google drive links
( put them in a zip first and then upload it )

**Comment by Anuken** [comment] 2021-03-27 13:13
UnitRadar output is cached and updated only a few times per second. Not a bug.

**Closed by Anuken** 2021-03-27 13:13 UTC
Labels: bug
