### ISSUE TITLE
Sprites misplaced and controlls are weird after phone goes to battery saving mode

### ISSUE THREAD

**Issue by LeggedMacQueen** [Anuken/Mindustry#2921] opened 2020-10-12 09:07 UTC
**Steps to reproduce**: Have an Android phone with battery saving mode. Both my current and former phones were Xiaomi.

**Link(s) to mod(s) used**: None. First time I saw it with a mod, but it is the same with vanilla.

**Save file**: N/A

**Crash report**: N/A

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Quezler** [comment] 2020-10-12 09:08
please add a screenshot.

**Comment by LeggedMacQueen** [comment] 2020-10-12 09:09
I cannot right now. I need low battery. doesn't work manually. only automatially.

Wait a bit.

**Comment by itcannotbe** [comment] 2020-10-12 10:28
Anuke: Can't reproduce. Won't fix.

**Comment by Anuken** [comment] 2020-10-12 13:57
Yep. Doesn't happen on any of my devices. Probably yet another Android quirk, restart your game or avoid power saving mode.

**Closed by Anuken** 2020-10-12 13:57 UTC
Labels: bug

**Comment by DeltaNedas** [comment] 2020-10-12 15:44
im guessing it changes mem allocated to the atlas so everything changes
