### ISSUE TITLE
Linux No Sound PulseAudio

### ISSUE THREAD

**Issue by SollyBunny** [Anuken/Mindustry#4737] opened 2021-02-19 22:33 UTC
**Platform**: *Linux*

**Build**: *125*

**Issue**: No audio is heard in any way

**Steps to reproduce**: Alsamixer + Pulseaudio + Jackd. If there is any audio stream no audio is heard at all anywhere (menu/ingame), if there is no audio stream then mindustry audio works fine (but other programmes will no longer be able to use audio)

**Link(s) to mod(s) used**: https://github.com/MindustryInside/AutoUpdater

**Save file**: NA

**(Crash) logs**:
> [I] Initialized Discord rich presence.
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ALSA lib pcm_dmix.c:1075:(snd_pcm_dmix_open) unable to open slave
[E] Failed to initialize audio, disabling sound: arc.util.ArcRuntimeException: Other error
	at arc.audio.Soloud.init(Native Method)
	at arc.audio.Audio.initialize(Audio.java:33)
	at arc.audio.Audio.<init>(Audio.java:23)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:36)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
[I] [GL] Version: OpenGL 4.6.0 / NVIDIA Corporation / GeForce GTX 1070/PCIe/SSE2
[I] [GL] Max texture size: 32768
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 15.0.2
[I] Loaded mod 'auto-updater' in 16.753616ms
[I] Total time to load: 2090
[I] Fetching community servers at https://raw.githubusercontent.com/Anuken/Mindustry/master/servers_v6.json
[I] Time to generate menu: 67.12207
[I] Fetched 22 community servers.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2021-02-19 22:55
Can't reproduce, won't fix. I've tried a lot of different Linux audio backends and the current setup is the only one that works reliably on most systems.

**Closed by Anuken** 2021-02-19 22:55 UTC
Labels: bug
