### ISSUE TITLE
Version 135 from itch.io crash on launch

### ISSUE THREAD

**Issue by LargePrime** [Anuken/Mindustry#6533] opened 2022-01-25 20:33 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
Version 135

**Issue**: *Explain your issue in detail.*

crash on launch see crash log

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
download zip, extract, launch, look at crash log
**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

none
 
**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

NA no save as game not start

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

https://paste.artixlinux.org/982995bd

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

search found this, but seemed unrelated? https://github.com/Anuken/Mindustry/issues?q=is%3Aissue+libarc64.so

**Comment by Anuken** [comment] 2022-01-25 20:54
This is caused by a native crash in audio initialization. I did not write the audio backend library, and I can't reproduce this anywhere, so this won't be fixed - unless something happens upstream.

**Comment by LargePrime** [comment] 2022-01-25 21:56
how can I pursue this upstream?

**Comment by Anuken** [comment] 2022-01-25 23:39
> how can I pursue this upstream?

You can't. I don't know what causes the crash.

> How can one launch without sound?

It's not possible without source modification.

> 126.2 works fine. What changed?

I was forced to switch audio backends due to [significant issues on certain distros.](https://github.com/Anuken/Mindustry/issues/6349)

**Comment by LargePrime** [comment] 2022-01-26 01:03
https://github.com/adoptium/adoptium-support/issues/436

**Comment by Anuken** [comment] 2022-01-26 02:26
Please close that issue - despite the link in the crash report, that crash is extremely unlikely to have anything to do with Adoptium or the JDK in general. As I mentioned above:

> It's probably related to miniaudio's pulseaudio backend, but it's useless to file a report without knowing whether this is actually the case or what the problem is.

**Comment by abrasmag3** [comment] 2022-01-31 20:17
I appear to have found the upstream cause, however I will not create an issue until this can be confirmed to some greater capacity. I was successfully able to load Mindustry by switching *audio session managers*. I switched from the provided pipewire-media-session to the alternative wireplumber, and it fixed my crash.

**Comment by abrasmag3** [comment] 2022-01-31 20:24
Nevermind, it appears to have worked once and then stopped. This is very confusing

**Comment by Anuken** [comment] 2022-01-31 20:28
You could test if it has been fixed by replacing `libarc64.so` in the compiled `mindustry.jar` with an [updated file](https://github.com/Anuken/Arc/blob/master/natives/natives-desktop/libs/libarc64.so) that I re-compiled recently with a newer version of MiniAudio, then launching the game with the old audio session manager.

If that still crashes, you could try compiling/running some of the [miniaudio examples](https://github.com/mackron/miniaudio) to try and narrow down the problem. (I have no experience debugging C code, and frankly this is my first time hearing of "audio session managers", so I can't be of much use there)

**Comment by fes0j** [comment] 2022-02-07 16:26
I tried the replacement  `libarc64.so`, but also got an error from midiaudio. 

Although that lead me to a new [issue](https://github.com/mackron/miniaudio/issues/427) over there that matches my error. So for anybody interested, maybe have a look on that development.

**Comment by Anuken** [comment] 2022-02-07 16:50
I've updated the shared library with the (potential) miniaudio fix. https://github.com/Anuken/Arc/commit/3ad7f0345b458dff04f80e214e62c98026801d05

**Comment by Anuken** [comment] 2022-02-07 17:37
Better than nothing, I suppose. Most likely another miniaudio bug; audio still works on my Ubuntu machine.

**Comment by fes0j** [comment] 2022-02-09 16:37
Sorry for getting back later. There is Audio now, but with the same issue that @weimzh [mentioned](https://github.com/mackron/miniaudio/issues/427#issuecomment-1033822629). It's crackly and mangled up.

**Comment by Anuken** [comment] 2022-02-09 17:05
I'll look into applying the `m_config.periodSizeInFrames = 1024` fix once the deve

**Comment by Anuken** [comment] 2022-02-10 13:27
The update has been applied - this should conclusively fix the problem.

**Comment by fes0j** [comment] 2022-02-10 21:02
So, Mindustry does definitely runs 100% again. But there was also a update to  [pipewire 0.3.45](https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.45). Reading the changelog I'm not sure, if this issue was solved there (Not very satisfying). 

Anyhow, thanks for investigating!

**Comment by Anuken** [comment] 2022-02-10 21:04
Either way, it works now - thanks for testing!

**Closed by Anuken** 2022-02-10 21:04 UTC
Labels: bug, wontfix
