### ISSUE TITLE
Almost whole campaign reset after I downloaded it on the steamdeck

### ISSUE THREAD

**Issue by scpoperative** [Anuken/Mindustry#10061] opened 2024-07-26 15:18 UTC
### Platforms

Windows

### Build

steam build 146

### Issue

I had Mindustry on my PC and got around 190 hours of playtime, I then got a steamdeck and downloaded the game. I started it on the steamdeck, and my campaign looked like in the screenshot.
![Bild_2024-07-26_170238870](https://github.com/user-attachments/assets/b567fd7f-35de-4a98-85dc-4934f7140a7d)
All blocks placed are the exact same, but almost everything else reset, like my research tree and all previously captured sectors went uncaptured

A similar thing happened when I tried to import my erekir campaign save files from mobile to the pc version, it worked but all erekir sectors went uncaptured but the blocks that I placed stayed the same

### Steps to reproduce

Import files from one device to another

For me it was like this:
I played the game on PC
I got a steamdeck and downloaded it there
Because of the bug my whole campaign broke
Steam uploaded that save file to the cloud
because of that its on my pc

### Save file

[save.zip](https://github.com/user-attachments/files/16393549/save.zip)

### Submission

- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.
- [X] I am not using Foo's Client, and have made sure the bug is not caused by mods I have installed.

**Comment by Mavment** [comment] 2024-07-26 21:16
Holy, this bug is very very very old, i had the same problem a while ago (in v5) when deleting mindustry on phone, downloading again and the loading save file, all sectors get marked as attacked, but after waiting for a while (not doing everything) they 1 by 1 somehow self defended, like i once came on survival sector from that savefile (in v7) and there was wave 789/40 and there was literally nothing built on map, also this stops working if you even once entered sector after bug

**Comment by Mavment** [comment] 2024-07-26 21:17
I though anuke fixed it a while ago cause i never experienced this since v5 lol

**Comment by Mavment** [comment] 2024-07-26 21:20
@scpoperative , just wait in planet view for like 2-3 hours, your sectors will become yours if you haven't entered them since bug, as for research tree, its probably unreturnable

**Comment by Anuken** [comment] 2024-07-27 02:25
Your settings/data file got wiped for whatever reason - unless I can reliably reproduce this I can't help you. Save imports work correctly for me.

**Closed by Anuken** 2024-07-27 02:25 UTC
Labels: bug

**Comment by scpoperative** [comment] 2024-07-27 06:18
so basically i cant save it and have to restart my whole campaign???
