### ISSUE TITLE
Multitasking issue

### ISSUE THREAD

**Issue by willis936** [Anuken/Mindustry#1138] opened 2019-11-27 19:22 UTC
**Platform**: iOS 13.2.3

**Build**: 100.2

**Issue**: The screen is a black when resuming a game.

**Steps to reproduce**:

1. Start or load a level.

2. Switch out of mindustry with multitasking.

3. Switch back to mindustry with multitasking.

**Comment by arinsarkisian** [comment] 2019-12-04 21:59
My mate has a similar issue: when he switches to another app or locks the screen and then returns to the game, his in-game UI is gone, but the rest of the game is still there and he can scroll around but that's about it.

Is there any kind of error log I can generate and submit?

He uses an iPhone XS Max.

**Comment by Anuken** [comment] 2019-12-07 15:25
Cannot reproduce on an iPhone 8. As there are no crashes, there won't be a log.

**Comment by cuikangyi** [comment] 2019-12-11 10:11
same issue in my iPhone7 with iOS13.3
the tools are missing
sorry my poor english
![29B5927F-35F7-472D-BF50-839246B3213E](https://user-images.githubusercontent.com/5945838/70612257-95ce5200-1c41-11ea-9fef-3979b7c844f1.png)

**Comment by cuikangyi** [comment] 2019-12-12 04:07
I have known  the reason why black screen, I open the Bloom option.
![2019-12-12 12 02](https://user-images.githubusercontent.com/5945838/70681795-987b8680-1cd7-11ea-8d2c-ed359987a6f6.png)

**Comment by Anuken** [comment] 2020-02-18 17:40
Fixed by disabling bloom on iOS until a new postprocessing system is integrated.

**Closed by Anuken** 2020-02-18 17:40 UTC
