### ISSUE TITLE
my game wont launch because of java bug

### ISSUE THREAD

**Issue by imawalmartbag** [Anuken/Mindustry#8491] opened 2023-04-08 14:19 UTC
Platform: windows 10

Build: 10909160

Issue: i tried to launch the game  and it crashed giving me a java related issue.

Steps to reproduce: 
1: go to your steam mindustry page.
2: launch the game through the play button.
3: wait for the game to launch > at this point, the game should launch for 1 sec and then crash.
4: crash report window indecate to go check the crash report with "no cap characters found in the font" > check the screenshot below
![Capture d’écran (2461)](https://user-images.githubusercontent.com/130231319/230726045-02277827-aedc-4c2d-b27b-32f2c0db502f.png)

Link(s) to mod(s) used: vanilla

(Crash) logs: [crash-report-04_08_2023_15_16_20.txt](https://github.com/Anuken/Mindustry/files/11183452/crash-report-04_08_2023_15_16_20.txt)

---

Place an X (no spaces) between the brackets to confirm that you have read the line below.
- [X] I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.
- [X] I have searched the closed and open issues to make sure that this problem has not already been reported.

**Comment by Anuken** [comment] 2023-04-08 14:27
Duplicate of #8483, wait for a bugfix release.

**Closed by Anuken** 2023-04-08 14:27 UTC
Labels: bug
