### ISSUE TITLE
Community vote for translations

### ISSUE THREAD

**Issue by feu-follet** [Anuken/Mindustry#1711] opened 2020-03-15 17:44 UTC
Some translations are false so you should add a vote to approve or disapprove the changes in the concerned community (for exemple if there is a new translation to russian, russian people will vote and if the majority agree with the changes, bundle will be updated, but else it won't)

**Comment by Quezler** [comment] 2020-03-15 17:47
People can already review the changes and/or comment on it, and automating it seems wrong 🤔
(And even when people from the community tend to disagree [stuff](https://github.com/Anuken/Mindustry/pull/1626#discussion_r383976948) still tends to get merged 😗)

**Comment by Anuken** [comment] 2020-03-15 18:06
I don't think this should be a vote by default. If there's a problem with a specific pull request, you should comment and let me/the translator know what the issue is. If (and only if) no resolution is reached, we could do something simple like counting the number of +1/-1 reactions on the final comment.

**Comment by feu-follet** [comment] 2020-03-16 14:14
Ok thank you

**Closed** 2020-03-16 14:14 UTC
Labels: invalid
