### ISSUE TITLE
Borderless Windowed cuts off 7 pixels on every edge of the screen

### ISSUE THREAD

**Issue by buthed010203** [Anuken/Mindustry#4360] opened 2021-01-17 16:43 UTC
**Platform**: Windows, this doesn't seem to happen on mac or linux.

**Build**: 122.1

**Issue**: The borderless windowed option cuts off 7 pixels on each edge of the screen which is kind of annoying, it has happened to both people that I asked to try it as well.
Borderless ![](https://vexera.is-ne.at/BTfKVy.png) Fullscreen ![](https://xenon.is-ne.at/80rVys.png)

**Steps to reproduce**: Enable the borderless window setting and notice how 7 pixels are cut off on every edge, restarting doesn't fix this.

**Save file**: This happens anywhere in the application

---

- [X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.** There was a similar issue posted over half a year ago but this is still an existing problem.

**Comment by Anuken** [comment] 2021-01-17 20:20
This doesn't happen on Linux; likely a bug in SDL. Won't fix.

**Closed by Anuken** 2021-01-17 20:20 UTC
Labels: bug

**Comment by LeoSko** [comment] 2021-01-18 12:06
Also duplicate of #2110
