### ISSUE TITLE
Mindustry campaign bug

### ISSUE THREAD

**Issue by Ishakkkk** [Anuken/Mindustry#8005] opened 2022-11-28 06:59 UTC
Windows

140.4 (V7)
so im playing in erekir and the ravine map needs tungsten to be able to go there, and it shows that it launches from lake, but lake dosent have no tungsten, so i cant launch, and im stuck, cuz i cant do anything else

i literally do not know, i went through the campgain, thats it

i use the time control mod, when u install it, it should show a slider bottom left for time speed

i cant, it says we dont support that file, i think thats cause im playing on steam

not a crash
---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Ishakkkk** [comment] 2022-11-28 07:20
i removed time travel and the bug is still there

**Comment by GleB2k19** [comment] 2022-11-28 13:00
Thats not a bug thats you being retarded. You need to be on a sector that has tungsten and launch from there. Its how it works

**Comment by GleB2k19** [comment] 2022-11-28 13:01
Please close the issue

**Comment by Ishakkkk** [comment] 2022-11-28 13:17
It dosent work, still automaticly launches from lake, lol

**Comment by Ishakkkk** [comment] 2022-11-28 13:20
i went to a sector nearby that had tungsten

**Comment by Ishakkkk** [comment] 2022-11-28 13:29
i just abandoned lake

**Comment by Ishakkkk** [comment] 2022-11-28 15:09
bruh this is bad, i beat ravine and i need surge to go to caldera, but i dont have surge since it goes from aegis

**Comment by Ishakkkk** [comment] 2022-11-28 16:29
You fucking cunt u didnt tell me n is a world map, fucking called me retarded and didnt help, what a bitch

**Closed** 2022-11-28 16:29 UTC
Labels: bug

**Comment by Bottinator22** [comment] 2022-11-28 16:37
...you previously had to pause, quit campaign, then go back in, just to access the planet map?

There are 2 buttons you have been ignoring for a long time

**Comment by Ishakkkk** [comment] 2022-11-28 16:54
i knew that n was world map but i didnt know that was i had to use

**Comment by Ishakkkk** [comment] 2022-11-28 16:56
i always thought it was the same as the save&quit button

**Comment by Ishakkkk** [comment] 2022-11-28 17:10
sometimes i use wrong wording

**Comment by Ishakkkk** [comment] 2022-11-28 18:34
the thing is i never use it
