### ISSUE TITLE
dying air units instantly go under the shadow layer

### ISSUE THREAD

**Issue by Quezler** [Anuken/Mindustry#4295] opened 2021-01-09 21:10 UTC
**Platform**: `Mac OS X x64`

**Build**: `bleeding-edge build 20499`

**Issue**: when any air unit dies while over shadowy terrain it **instantly** starts to render under it, which looks kinda weird:
(not sure if this is a bug or intended, but worth getting a definitive answer to)

![Screen Shot 2021-01-09 at 22 05 57](https://user-images.githubusercontent.com/3179271/104108728-3e2c6b00-52c7-11eb-986b-3ca81979bbcb.png)
![Screen Shot 2021-01-09 at 22 05 59](https://user-images.githubusercontent.com/3179271/104108729-3f5d9800-52c7-11eb-8efe-306aba021b91.png)

**Steps to reproduce**: make any air unit die while over shadowed terrain & observe.

**Link(s) to mod(s) used**: `[DeltaNedas/dev-mode:1.3.0]`

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*
- [ ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2021-01-09 21:11
Duplicate of #3391

**Closed by Anuken** 2021-01-09 21:11 UTC
