### ISSUE TITLE
Junctions not transferring to Base

### ISSUE THREAD

**Issue by ICrowleyI** [Anuken/Mindustry#70] opened 2018-01-12 21:48 UTC
It seems that junctions do not transfer items to base.
In the gif, the coal should be added to the ressource pool.
![junction not transferring items to base](https://user-images.githubusercontent.com/30113543/34896490-5e275d74-f7ea-11e7-8508-110cb97fe259.gif)

**Comment by Anuken** [comment] 2018-01-15 20:13
Should be fixed in the latest beta; I can't reproduce it anymore.

**Closed by Anuken** 2018-01-15 20:13 UTC
