### ISSUE TITLE
Music plays again in 0%

### ISSUE THREAD

**Issue by TotalFoc** [Anuken/Mindustry#1730] opened 2020-03-19 21:10 UTC
Platform: android 
Build: 104.5
Issue: music play in 0%

**Comment by DeltaNedas** [comment] 2020-03-19 21:43
duplicate of #1504
Anuke and I cannot replicate it.

**Closed** 2020-03-19 22:48 UTC

**Comment by Austin5003** [comment] 2020-03-19 23:51
Platform: PC
Build: 104.5
Same issue
Same sound will persist instead of playing the appropriate track for the menu you're in
Caused by setting music volume to 0 while a track is playing
Suggested solution: call a track stop when music volume is set to 0
