### ISSUE TITLE
FPS showing incorrectly or setting incorrectly.

### ISSUE THREAD

**Issue by unknownzzzz** [Anuken/Mindustry#2583] opened 2020-09-18 02:01 UTC
Set FPS to 145.  My monitor is a 144hz display.
FPS showing on screen is 126.

Either it is at 144 and showing 126?
Or it's set to 145, but being set to 126 in code?
![image](https://user-images.githubusercontent.com/71476513/93546653-4421c900-f931-11ea-95d9-28e20756c955.png)
![image](https://user-images.githubusercontent.com/71476513/93546670-4e43c780-f931-11ea-823d-9c6601c122fe.png)

**Comment by ninjassifi** [comment] 2020-09-18 02:07
Idk. Maybe you actually have that many fps. If it was all the time, than it would be a problem.

**Comment by Anuken** [comment] 2020-09-18 02:17
If your monitor is 144HZ, disable the FPS cap and enable VSync.

This can be caused by any number of things, and none of them can be fixed by me.

**Closed by Anuken** 2020-09-18 02:17 UTC
Labels: bug

**Comment by unknownzzzz** [comment] 2020-09-18 03:31
Vsync is on, I tried with it off and same results.
My computer can easily handle 300 FPS.  Especially in the small campaign maps.

FPS slider setting vs ingame display for FPS:
60 FPS gives 56-59.
120 FPS gives 111-114
145 FPS giver 124-126
Unlimited will give the 144 FPS.

Seems like a misread of the slider, or the game is predicting clean map performance thus actual FPS is inaccurate.
