### ISSUE TITLE
Bug Report Steam 6.0. Alpha testing

### ISSUE THREAD

**Issue by Mothership007** [Anuken/Mindustry#2616] opened 2020-09-19 15:43 UTC
Platform: *Android/iOS/Mac/Windows/Linux*

Build: steam build 105

**Issue**: upon arriving on wave 34 on sector 145, bunch of daggers spawned, however, these daggers were clumped tightly together ignoring their hitbox, these super-clumped daggers were totally missing their hitbox, and were ignored by all kinds turrets. Upon attempting to shoot them, bullets passed through them further confirming their missing hitbox. This bug caused me and my friend to loose, and we dont want this happen to anyone else in same or further waves.  

Steps to reproduce: I reached the wave 34. on sector 145

[MIndustry saves.zip.zip](https://github.com/Anuken/Mindustry/files/5250117/MIndustry.saves.zip.zip)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-09-19 16:20
Duplicate of #2582 (or similar enough)

**Closed by Anuken** 2020-09-19 16:20 UTC
Labels: bug
