### ISSUE TITLE
Importing Github Mod on Steam Version

### ISSUE THREAD

**Issue by dbnaruto** [Anuken/Mindustry#1021] opened 2019-11-09 00:54 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*
Linux (Ubuntu 18.04 LTS) -- Using OpenJDK 11.0.4 2019-07-16
(Not sure if that matters for the Steam Version)

**Build**: *The build number under the title in the main menu. Required.*
Steam Build 99.12

**Issue**: *Explain your issue in detail.*
When trying to import the "Github Mod" in the Mods menu, the mod can not be imported. On first try a No Class Exception is thrown (images 1 & 2). On second attempt a screen displays devices doe not support this feature (image 3). I'm not wholly sure if this is a bug, or just a very long way to say "Use the Steam Workshop" :P.

**Steps to reproduce**: *How you happened across the issue, and what you were doing at the time.*
1. Open Mod menu
2. Click import Github Mod
3. See first message
4. Close windows
5. Click import Github Mod again
6. See second message

Images Attched:
1: ![image](https://user-images.githubusercontent.com/29187721/68519695-a4030a00-0260-11ea-82ad-fd06a133ebc6.png)
2: ![image](https://user-images.githubusercontent.com/29187721/68519866-cfd2bf80-0261-11ea-895e-6567d88b479e.png)
3: ![image](https://user-images.githubusercontent.com/29187721/68519773-183dad80-0261-11ea-80c2-dac844128d12.png)

**Comment by Type-01** [comment] 2019-11-09 01:14
I can confirm that this error does exist and works on itch.io release as well, with the same version.

**Comment by Anuken** [comment] 2019-11-09 02:11
Will be fixed for the next release. Problem was caused by aggressive JRE minimization.

**Closed by Anuken** 2019-11-09 02:11 UTC

**Comment by dbnaruto** [comment] 2019-11-09 02:13
Cool, thanks for the quick response!
