### ISSUE TITLE
Sector Reset (iOS)

### ISSUE THREAD

**Issue by OinkyPlayz** [Anuken/Mindustry#3590] opened 2020-11-25 14:36 UTC
**Platform**: iOS

**Build**: Beta Build 117

**Issue**: Suddenly, the FPS of a sector would turn very very bad, and then mindustry will crash. After it is rebooted, the sector which was affected would have its data deleted. (Everything built and all resources in it, waves done and capturing will also be deleted.)

**Steps to reproduce**: I was in Ground Zero upgrading production there, I am not quite sure what caused it, but it happened after I started scrap dissembling/ sending the resource into a recently upgraded Nucleus Core/ Turned some resource into Phase Phabric.

**Link(s) to mod(s) used**: N/A 

**Save file**: I am not sure how to retrieve this information, I apologise.

**Crash report**: crash_1606314787388.txt

Mindustry has crashed. How unfortunate.
Report this at https://github.com/Anuken/Mindustry/issues/new?labels=bug&template=bug_report.md

Version: beta build 117
OS: iOS x32
Java Version: 0
Java Architecture: null
0 Mods

> Runtime: 'arc.util.ArcRuntimeException: Error copying source file: /private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Mindustry/mindustry-data-export/saves/sector-serpulo-20.msav (absolute)
To destination: /var/mobile/Containers/Data/Application/65017CC9-5390-469E-AD31-153D554930B1/Documents/sector-serpulo-20.msav (absolute)'
IOSGraphics.runProtected: 256
IOSGraphics.update: 235
IOSGraphics$IOSGraphicsDelegate.update: 570
IOSGraphics$IOSGraphicsDelegate.$cb$glkViewControllerUpdate$: -1
UIApplication.main: -2
UIApplication.main: 446
IOSLauncher.main: 254
> ArcRuntime: 'Error copying source file: /private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Mindustry/mindustry-data-export/saves/sector-serpulo-20.msav (absolute)
To destination: /var/mobile/Containers/Data/Application/65017CC9-5390-469E-AD31-153D554930B1/Documents/sector-serpulo-20.msav (absolute)'
Fi.copyFile: 112
Fi.copyTo: 829
IOSLauncher.lambda$openURL$5: 222
IOSLauncher$$Lambda$3.run: -1
IOSApplication.processRunnables: 241
IOSGraphics$$Lambda$2.run: -1
IOSGraphics.runProtected: 246
IOSGraphics.update: 235
IOSGraphics$IOSGraphicsDelegate.update: 570
IOSGraphics$IOSGraphicsDelegate.$cb$glkViewControllerUpdate$: -1
UIApplication.main: -2
UIApplication.main: 446
IOSLauncher.main: 254
> ArcRuntime: 'Error reading file: /private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Mindustry/mindustry-data-export/saves/sector-serpulo-20.msav (absolute)'
Fi.read: 206
Fi.copyFile: 110
Fi.copyTo: 829
IOSLauncher.lambda$openURL$5: 222
IOSLauncher$$Lambda$3.run: -1
IOSApplication.processRunnables: 241
IOSGraphics$$Lambda$2.run: -1
IOSGraphics.runProtected: 246
IOSGraphics.update: 235
IOSGraphics$IOSGraphicsDelegate.update: 570
IOSGraphics$IOSGraphicsDelegate.$cb$glkViewControllerUpdate$: -1
UIApplication.main: -2
UIApplication.main: 446
IOSLauncher.main: 254
> FileNotFound: '/private/var/mobile/Library/Mobile Documents/com~apple~CloudDocs/Mindustry/mindustry-data-export/saves/sector-serpulo-20.msav: open failed: EPERM (Operation not permitted)'
IoBridge.open: 409
FileInputStream.<init>: 78
Fi.read: 203
Fi.copyFile: 110
Fi.copyTo: 829
IOSLauncher.lambda$openURL$5: 222
IOSLauncher$$Lambda$3.run: -1
IOSApplication.processRunnables: 241
IOSGraphics$$Lambda$2.run: -1
IOSGraphics.runProtected: 246
IOSGraphics.update: 235
IOSGraphics$IOSGraphicsDelegate.update: 570
IOSGraphics$IOSGraphicsDelegate.$cb$glkViewControllerUpdate$: -1
UIApplication.main: -2
UIApplication.main: 446
IOSLauncher.main: 254
> Errno: 'open failed: EPERM (Operation not permitted)'
Posix.open: -2
BlockGuardOs.open: 110
IoBridge.open: 393
FileInputStream.<init>: 78
Fi.read: 203
Fi.copyFile: 110
Fi.copyTo: 829
IOSLauncher.lambda$openURL$5: 222
IOSLauncher$$Lambda$3.run: -1
IOSApplication.processRunnables: 241
IOSGraphics$$Lambda$2.run: -1
IOSGraphics.runProtected: 246
IOSGraphics.update: 235
IOSGraphics$IOSGraphicsDelegate.update: 570
IOSGraphics$IOSGraphicsDelegate.$cb$glkViewControllerUpdate$: -1
UIApplication.main: -2
UIApplication.main: 446
IOSLauncher.main: 254

last log:
[I] [GL] Version: GLES 2.0.0 / Apple Inc. / Apple A11 GPU
[I] [GL] Max texture size: 4096
[I] [GL] Using OpenGL 2 context.
[I] [JAVA] Version: 0
[W] Shader shaders/screenspace.vert | shaders/mud.frag:
Fragment shader:
WARNING: 0:27: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/tar.frag:
Fragment shader:
WARNING: 0:27: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[W] Shader shaders/screenspace.vert | shaders/slag.frag:
Fragment shader:
WARNING: 0:30: Overflow in implicit constant conversion, minimum range for lowp float is (-2,2)

[I] [IOSApplication] resumed
[I] Total time to load: 1852
[I] Time to generate menu: 15.9285
[I] Fetched 5 global servers.

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [X ] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [X ] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-11-25 14:40
The crash report posted isn't relevant to the issue - it's from something completely unrelated.

I can't reproduce this on any device, so it won't be fixed.

**Closed by Anuken** 2020-11-25 14:40 UTC
Labels: bug
