### ISSUE TITLE
Map editor core bug

### ISSUE THREAD

**Issue by sample-text-here** [Anuken/Mindustry#2902] opened 2020-10-11 02:16 UTC
**Note**: Do not report any new bugs directly relating to the v6 campaign. They will not be fixed or considered at this time.

**Platform**: Windows
**Build**: be 10375

**Issue**: I opened a map i was working on in bleeding edge, and this happened?
![image](https://user-images.githubusercontent.com/56274831/95668661-e9445180-0b2b-11eb-97a9-de35d11e7bb6.png)
And editing in game
![image](https://user-images.githubusercontent.com/56274831/95668659-e5183400-0b2b-11eb-8661-8f117fe855f4.png)

**Steps to reproduce**: I have no idea, I make the map in the previous bleeding edge, and when I opened it up it glitched and did this.

**Link(s) to mod(s) used**: none

**Save file**:
[broken.zip](https://github.com/Anuken/Mindustry/files/5360500/broken.zip) (This is the zipped map file)

**Crash report**: none

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2020-10-11 13:01
I can't reproduce the problem with your save file, and trying to place cores everywhere manually doesn't do it either. This won't be fixed.

**Closed by Anuken** 2020-10-11 13:01 UTC
Labels: bug
