### ISSUE TITLE
Text in Message block isn't restored in Schematics 

### ISSUE THREAD

**Issue by famo** [Anuken/Mindustry#1264] opened 2019-12-28 15:53 UTC
**Platform**: *Linux*

**Build**: *5.0 Build 101.1*

**Issue**: *Text in Message block isn't restored in Schematics.*

**Steps to reproduce**: 
Place a message block, enter text and copy or save it with `f`. After placing the copy the message block is empty.

Additional note:
The message block is useful for more complicated schematics, as you can put instructions inside. Also for power designs you can inform about the power output etc....

**Comment by Quezler** [comment] 2019-12-28 15:54
not a bug.

**Comment by famo** [comment] 2019-12-28 15:55
Ah, why if I may ask?

**Comment by Quezler** [comment] 2019-12-28 15:56
my wild guess is that schematics only store 1 configurable integer value per block (e.g. which filter is set on a sorter/unloader/etc, and that simply cannot accommodate for custom strings of text, i might be wrong though

**Comment by famo** [comment] 2019-12-28 16:02
Ok, so I'll leave it open for now.

**Comment by Quezler** [comment] 2019-12-28 16:03
chances are anuke will close it pretty soon then

**Comment by Anuken** [comment] 2019-12-28 16:19
Schematics store only block configuration, as said above. Text is not considered. block configuration.

**Closed by Anuken** 2019-12-28 16:19 UTC
