### ISSUE TITLE
Auto bridge bug

### ISSUE THREAD

**Issue by JosherIsFun** [Anuken/Mindustry#4946] opened 2021-03-17 04:01 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.* 126.1

**Issue**: *Explain your issue in detail.*
Bridge conveyors gets built via auto bridge EVEN before unlocking bridge conv

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*
1. Go to mindustry
2. Go to campaign
3. Built in straight line
4. See bug

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*
[issue.zip](https://github.com/Anuken/Mindustry/files/6153668/issue.zip)

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ x

Uploading SVID_20210317_115342_1.mp4…

] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by joshuaptfan** [comment] 2021-03-17 04:11
Duplicate of #4875, which has already been fixed.

**Comment by Qvertyes** [comment] 2021-03-17 04:19
close it

**Closed** 2021-03-17 13:15 UTC
Labels: bug
