### ISSUE TITLE
A few issue with the PPT

### ISSUE THREAD

**Issue by EclipseTheOldOne** [Anuken/Mindustry#6486] opened 2022-01-12 05:16 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*
Binbow 10
**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*
v7 release build 135
also tested in BE build 22284
**Issue**: *Explain your issue in detail.*
Basically i founded a few issue with the Payload Prop. Tower.

Payload Prop Tower Perfering Shooting than Outputing

![bug](https://user-images.githubusercontent.com/43229798/149067513-4422f8e3-29cd-4293-b4c4-84d715138578.gif)

Construction Process are Rotated

![bug1](https://user-images.githubusercontent.com/43229798/149067518-406cc83a-aa84-4ee2-bfe8-8542da2a52c9.gif)

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

First one - Build 2 PPT shooting each other, the payload won't output
Second - Build PPT tower rotated

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

https://drive.google.com/file/d/1djYkt57YZWKWughVnCp7w1vFb3ZvVNOm/view?usp=sharing

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

okay

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [x] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [x] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by MrDuck557** [comment] 2022-01-12 13:57
> Build 2 PPT shooting each other, the payload won't output

Similar behavior with regular mass driver
except that regular md outputs one item every time it recieves

**Comment by Anuken** [comment] 2022-01-12 14:51
> Payload Prop Tower Perfering Shooting than Outputing
> Build 2 PPT shooting each other, the payload won't output

That's what they're supposed to do. This is a nonsensical setup; not a bug.

> Build PPT tower rotated

This is in the same class of issues as reconstructor bases appearing rotated while building; is fixed in the v7 development branch.

**Closed by Anuken** 2022-01-12 14:51 UTC
Labels: bug
