### ISSUE TITLE
Broken placing buildings by drag'n'drop

### ISSUE THREAD

**Issue by wasikuss** [Anuken/Mindustry#1336] opened 2020-01-08 13:04 UTC
**Platform**: Android

**Build**: 102.3

**Issue**: [Gif](https://gifyu.com/image/mjPG) 

**Steps to reproduce**: Try to build using drag'n'drop

**Comment by Quezler** [comment] 2020-01-08 13:27
what exactly is not working as expected?

**Comment by Anuken** [comment] 2020-01-08 13:28
Works on my devices. Restart your phone or reinstall the app to see if it still happens.

**Comment by DeltaNedas** [comment] 2020-01-08 17:16
how did you make a 35mb gif!?

**Comment by DeltaNedas** [comment] 2020-01-08 17:21
and besides, you need to deselect your block, hold empty space, then drag
WOMM

**Comment by wasikuss** [comment] 2020-01-08 17:58
I've made gif via online service mp42gif. Very inefficient... After restart problem disappeared. But after some time happened again. So for now only restart of game helps. But problem exists. I'll record this behavior.

**Comment by wasikuss** [comment] 2020-01-08 18:12
https://gifyu.com/image/m08z
https://gifyu.com/image/m08M

Happened right after resume game. First is without long press, second with. So both behavior pans screen disallowing placing buildings along line.

**Comment by DeltaNedas** [comment] 2020-01-09 17:46
womm and woam (works on anukes machine(s))

**Comment by Anuken** [comment] 2020-03-28 03:20
Closing:
- I can't reproduce this, or even intentionally induce it.
- It happens randomly without any particular reason, and disappears during phone/app restarts - always a bad sign.
- Historically, Android bugs that appear randomly and disappear during restarts have been impossible to diagnose or fix reliably (example: the minimap bug, which disappeared on an identical re-install during testing and eventually was completely eliminated with no code changes involved)
- I don't know if it still happens.
- I have no way of fixing it unless someone provides more information, which isn't happening.

**Closed by Anuken** 2020-03-28 03:20 UTC
