### ISSUE TITLE
Crashes on startup loading screen

### ISSUE THREAD

**Issue by Delstrom2** [Anuken/Mindustry#5070] opened 2021-04-06 21:30 UTC
**Platform**: *Android/iOS/Mac/Windows/Linux*

Windows 32bit (technically a windows arm64 device, but running the 32bit version of the app)

**Build**: *The build number under the title in the main menu. Required. "LATEST" IS NOT A VERSION, I NEED THE EXACT BUILD NUMBER OF YOUR GAME.*

Release build 126.2. I think this is the number you're looking for. This is the Itch.io version as I was never able to figure out how to use the GitHub release version

**Issue**: *Explain your issue in detail.*

Game opens and the initial loading screen gets to about 6 "triangles" into the loading bar on each side and then crashes.

**Steps to reproduce**: *How you happened across the issue, and what exactly you did to make the bug happen.*

Opened up the game. Waited. Crashed

**Link(s) to mod(s) used**: *The mod repositories or zip files that are related to the issue, if applicable.*

No mods

**Save file**: *The (zipped) save file you were playing on when the bug happened. THIS IS REQUIRED FOR ANY ISSUE HAPPENING IN-GAME OR IN MULTIPLAYER, REGARDLESS OF WHETHER YOU THINK IT HAPPENS EVERYWHERE. DO NOT DELETE OR OMIT THIS LINE UNLESS YOU ARE SURE THAT THE ISSUE DOES NOT HAPPEN IN-GAME. IF YOU DO NOT HAVE A SAVE, DON'T WASTE TIME OPENING THIS ISSUE.*

No save file created yet.

If you remove the line above without reading it properly and understanding what it means, I will reap your soul. Even if you're playing on someone's server, you can still save the game to a slot.

**(Crash) logs**: *Either crash reports from the crash folder, or the file you get when you go into Settings -> Game Data -> Export Crash logs. REQUIRED if you are reporting a crash.*

Version: release build 126.2
OS: Windows 10 x32
Java Version: 1.8.0_201-1-ojdkbuild
Java Architecture: 32
0 Mods

arc.util.ArcRuntimeException: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: contentcreate
	at arc.assets.AssetManager.handleTaskError(AssetManager.java:670)
	at arc.assets.AssetManager.update(AssetManager.java:442)
	at arc.assets.AssetManager.update(AssetManager.java:465)
	at mindustry.ClientLauncher.update(ClientLauncher.java:143)
	at arc.backend.sdl.SdlApplication.listen(SdlApplication.java:160)
	at arc.backend.sdl.SdlApplication.loop(SdlApplication.java:148)
	at arc.backend.sdl.SdlApplication.<init>(SdlApplication.java:44)
	at mindustry.desktop.DesktopLauncher.main(DesktopLauncher.java:36)
Caused by: arc.util.ArcRuntimeException: Couldn't load dependencies of asset: contentcreate
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:105)
	at arc.assets.AssetLoadingTask.update(AssetLoadingTask.java:74)
	at arc.assets.AssetManager.updateTask(AssetManager.java:591)
	at arc.assets.AssetManager.update(AssetManager.java:440)
	... 6 more
Caused by: arc.util.ArcRuntimeException: java.lang.NullPointerException
	at arc.util.async.AsyncResult.get(AsyncResult.java:34)
	at arc.assets.AssetLoadingTask.handleAsyncLoader(AssetLoadingTask.java:103)
	... 9 more
Caused by: java.lang.NullPointerException
	at mindustry.graphics.g3d.PlanetGrid.subdividedGrid(PlanetGrid.java:149)
	at mindustry.graphics.g3d.PlanetGrid.create(PlanetGrid.java:60)
	at mindustry.type.Planet.<init>(Planet.java:82)
	at mindustry.content.Planets$2.<init>(Planets.java:45)
	at mindustry.content.Planets.load(Planets.java:45)
	at mindustry.core.ContentLoader.createBaseContent(ContentLoader.java:67)
	at mindustry.ClientLauncher.lambda$setup$3(ClientLauncher.java:95)
	at arc.assets.AssetManager$1.loadAsync(AssetManager.java:329)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:53)
	at arc.assets.AssetLoadingTask.call(AssetLoadingTask.java:17)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

---

*Place an X (no spaces) between the brackets to confirm that you have read the line below.*  
- [ X] **I have updated to the latest release (https://github.com/Anuken/Mindustry/releases) to make sure my issue has not been fixed.**
- [ X] **I have searched the closed and open issues to make sure that this problem has not already been reported.**

**Comment by Anuken** [comment] 2021-04-06 21:38
Cannot reproduce on any platform - won't fix.

> technically a windows arm64 device

This is not a supported architecture.

**Closed by Anuken** 2021-04-06 21:38 UTC
Labels: bug
